"""Additional bundled environment catalog data for planning-first decomposition."""

from __future__ import annotations


ELECTRICAL_SUBSTATION_CATALOG = {
    "id": "electrical_substation",
    "name": "Electrical Substation",
    "sector": "Transmission / Distribution / Utility",
    "description": (
        "Reference decomposition of an electrical substation, including switching authorities, control-house assets, "
        "protection and automation systems, station networking, remote access, and restoration dependencies."
    ),
    "context_presets": ["electrical_substation"],
    "nodes": [
        {
            "id": "substation_people_roles",
            "parent_id": None,
            "label": "People, Utility Coordination, and Trusted Parties",
            "category": "people",
            "description": "Relay engineers, switching authorities, line crews, control-centre staff, and OEM support paths that shape access and restoration.",
            "attack_surfaces": ["Switching approvals", "Relay setting changes", "Vendor trust", "Emergency dispatch"],
        },
        {
            "id": "relay_ops_engineers",
            "parent_id": "substation_people_roles",
            "label": "Relay, Protection, and Operations Engineers",
            "category": "people",
            "description": "Engineers with authority over relay settings, breaker sequences, bay logic, and abnormal-event handling.",
        },
        {
            "id": "switching_line_crews",
            "parent_id": "substation_people_roles",
            "label": "Switching Authorities and Line Crews",
            "category": "people",
            "description": "Field staff coordinating isolations, maintenance permits, switching orders, and post-fault restoration.",
        },
        {
            "id": "substation_integrators_oems",
            "parent_id": "substation_people_roles",
            "label": "Integrators, OEMs, and Specialist Vendors",
            "category": "people",
            "description": "Third parties maintaining relays, protection firmware, telecoms, batteries, or station automation servers.",
            "management_interfaces": ["Vendor laptops", "Relay engineering suites", "Support portals"],
        },
        {
            "id": "substation_physical",
            "parent_id": None,
            "label": "Physical Yard, Control House, and Field Access",
            "category": "physical",
            "description": "Perimeter fencing, control houses, marshalling kiosks, relay cabinets, breaker enclosures, and DC auxiliary systems.",
            "telemetry": ["Fence alarms", "Control-house access events", "CCTV", "Work permits"],
        },
        {
            "id": "yard_control_house",
            "parent_id": "substation_physical",
            "label": "Perimeter, Yard, and Control House",
            "category": "physical",
            "description": "External access into the yard, control building, cable trenches, and operator work areas.",
        },
        {
            "id": "breaker_transformer_cabinets",
            "parent_id": "substation_physical",
            "label": "Breaker Panels, Transformer Bays, and Relay Cabinets",
            "category": "physical",
            "description": "Field equipment and cabinets where protection, trip circuits, and measurement wiring converge.",
        },
        {
            "id": "battery_dc_auxiliary",
            "parent_id": "substation_physical",
            "label": "Battery, DC Auxiliary, and Station Service Systems",
            "category": "service",
            "description": "Substation batteries, chargers, DC boards, and auxiliary power needed for protection and breaker operation.",
        },
        {
            "id": "substation_protection_control",
            "parent_id": None,
            "label": "Protection, Control, and Automation Systems",
            "category": "ot",
            "description": "IEDs, protective relays, bay controllers, RTUs, HMIs, and engineering stations controlling local grid behaviour.",
            "attack_surfaces": ["Relay logic uploads", "Local serial ports", "Engineering workstations", "Firmware packages"],
        },
        {
            "id": "ieds_relays_bay",
            "parent_id": "substation_protection_control",
            "label": "IEDs, Protective Relays, and Bay Controllers",
            "category": "safety",
            "description": "Core automation assets controlling trips, breaker states, synch checks, and interlocking.",
            "common_protocols": ["IEC 61850 MMS", "GOOSE", "Sampled Values", "DNP3"],
            "example_technologies": ["SEL", "GE Multilin", "ABB Relion", "Siemens SIPROTEC"],
        },
        {
            "id": "rtu_hmi_eng_substation",
            "parent_id": "substation_protection_control",
            "label": "RTUs, HMIs, and Engineering Workstations",
            "category": "ot",
            "description": "Supervisory and engineering assets used to monitor bays, issue controls, and modify protection settings.",
        },
        {
            "id": "substation_network_remote",
            "parent_id": None,
            "label": "Station Networking, Timing, and Remote Access",
            "category": "networking",
            "description": "Station bus, process bus, serial gateways, utility WAN links, and remote-maintenance paths into the site.",
            "telemetry": ["Switch logs", "Router events", "Remote-access logs", "PTP/GPS alarms"],
        },
        {
            "id": "station_process_bus",
            "parent_id": "substation_network_remote",
            "label": "Station Bus, Process Bus, and Serial Gateways",
            "category": "networking",
            "description": "East-west communications between relays, HMIs, merging units, and legacy serial devices.",
            "common_protocols": ["IEC 61850", "DNP3", "IEC 60870-5-104", "Serial over IP"],
        },
        {
            "id": "wan_scada_backhaul",
            "parent_id": "substation_network_remote",
            "label": "Utility WAN, SCADA Backhaul, and Remote Engineering",
            "category": "networking",
            "description": "Carrier, microwave, fibre, and dispatch links connecting the substation to control centres and support teams.",
        },
        {
            "id": "gps_timing_sync",
            "parent_id": "substation_network_remote",
            "label": "GPS, PTP, and Time Synchronisation",
            "category": "networking",
            "description": "Timing sources used by disturbance recording, event ordering, and protection coordination.",
        },
        {
            "id": "substation_it_support",
            "parent_id": None,
            "label": "Control-Centre, Enterprise, and Support Systems",
            "category": "it",
            "description": "SCADA masters, outage management, asset inventory, identity, and utility business systems shaping substation access.",
            "attack_surfaces": ["SCADA credentials", "Asset-management workflows", "Support tickets", "Patch distribution"],
        },
        {
            "id": "scada_outage_asset",
            "parent_id": "substation_it_support",
            "label": "SCADA Masters, Outage Management, and Asset Systems",
            "category": "it",
            "description": "Central utility platforms that issue telemetry requests, switching coordination, and maintenance context to the site.",
        },
        {
            "id": "identity_docs_substation",
            "parent_id": "substation_it_support",
            "label": "Identity, Documentation, and Engineering Records",
            "category": "service",
            "description": "Directory services, drawings, relay settings archives, and operational records relied on during change and recovery.",
        },
        {
            "id": "substation_monitoring_recovery",
            "parent_id": None,
            "label": "Monitoring, Disturbance Review, and Recovery Process",
            "category": "monitoring",
            "description": "SOE logs, disturbance records, switching discipline, and change governance that shape detection and restoration quality.",
            "telemetry": ["SOE logs", "Disturbance files", "Relay event logs", "Switching records"],
        },
        {
            "id": "soe_fault_analysis",
            "parent_id": "substation_monitoring_recovery",
            "label": "SOE, Fault Records, and Event Analysis",
            "category": "monitoring",
            "description": "Operational evidence used to distinguish equipment faults, misoperation, and malicious relay manipulation.",
        },
        {
            "id": "settings_switching_governance",
            "parent_id": "substation_monitoring_recovery",
            "label": "Settings Governance, Switching, and Restoration",
            "category": "process",
            "description": "Approval paths for relay changes, switching orders, black-start dependencies, and service restoration sequencing.",
        },
    ],
}


WATER_TREATMENT_PLANT_CATALOG = {
    "id": "water_treatment_plant",
    "name": "Water Treatment Plant",
    "sector": "Water Utility / Treatment / Municipal OT",
    "description": (
        "Reference decomposition of a water treatment plant, including operators and municipal support, physical process areas, "
        "SCADA and dosing controls, remote telemetry, water-quality safeguards, and compliance-driven operations."
    ),
    "context_presets": ["water_treatment_plant"],
    "nodes": [
        {
            "id": "water_people_roles",
            "parent_id": None,
            "label": "People, Operators, and Trusted Parties",
            "category": "people",
            "description": "Plant operators, lab analysts, municipal IT, integrators, and chemical suppliers who influence access and safety decisions.",
            "attack_surfaces": ["Remote support", "Shared credentials", "Maintenance callouts", "Chemical vendor trust"],
        },
        {
            "id": "water_ops_lab",
            "parent_id": "water_people_roles",
            "label": "Operators, Supervisors, and Lab Staff",
            "category": "people",
            "description": "Personnel managing treatment state, dosing decisions, water-quality verification, and alarm response.",
        },
        {
            "id": "water_integrators_contractors",
            "parent_id": "water_people_roles",
            "label": "Integrators, Contractors, and Chemical Suppliers",
            "category": "people",
            "description": "Third parties maintaining PLCs, analyzers, remote access, dosing skids, and process instrumentation.",
        },
        {
            "id": "municipal_it_support",
            "parent_id": "water_people_roles",
            "label": "Municipal IT and Administrative Support",
            "category": "people",
            "description": "Shared IT teams supporting identity, remote access, file services, and business systems adjacent to the plant.",
        },
        {
            "id": "water_physical_process",
            "parent_id": None,
            "label": "Physical Plant, Process Areas, and Site Access",
            "category": "physical",
            "description": "Intake, treatment trains, chemical rooms, pump galleries, reservoirs, and physical paths into control panels or field assets.",
            "telemetry": ["Door access events", "CCTV", "Tank level alarms", "Work permits"],
        },
        {
            "id": "intake_process_buildings",
            "parent_id": "water_physical_process",
            "label": "Intake, Clarification, Filtration, and Process Buildings",
            "category": "physical",
            "description": "Core treatment stages and process equipment that can be disrupted or manipulated through physical or cyber access.",
        },
        {
            "id": "chemical_storage_dosing",
            "parent_id": "water_physical_process",
            "label": "Chemical Storage, Dosing Rooms, and Feed Skids",
            "category": "physical",
            "description": "Storage and dosing infrastructure for chlorine, coagulants, caustic, fluoride, and other treatment chemicals.",
        },
        {
            "id": "pumps_remote_sites",
            "parent_id": "water_physical_process",
            "label": "Pump Stations, Reservoirs, and Remote Sites",
            "category": "service",
            "description": "Distributed assets such as booster pumps, remote telemetry stations, or reservoirs linked into plant operations.",
        },
        {
            "id": "water_ot_control",
            "parent_id": None,
            "label": "SCADA, PLCs, and Process Control",
            "category": "ot",
            "description": "Supervisory control, engineering stations, PLCs, RTUs, analyzers, and process skids controlling treatment and distribution.",
            "attack_surfaces": ["HMI screens", "Engineering software", "PLC logic downloads", "Instrument calibration paths"],
        },
        {
            "id": "water_scada_hmi_eng",
            "parent_id": "water_ot_control",
            "label": "SCADA, HMIs, and Engineering Workstations",
            "category": "ot",
            "description": "Operator and engineering systems used to observe the plant and change process setpoints or automation logic.",
            "example_technologies": ["Ignition", "Wonderware", "FactoryTalk", "iFIX"],
        },
        {
            "id": "water_plc_rtu_process",
            "parent_id": "water_ot_control",
            "label": "PLCs, RTUs, and Treatment Process Skids",
            "category": "ot",
            "description": "Control endpoints managing pumps, valves, mixers, dosing pumps, and remote water assets.",
            "common_protocols": ["Modbus", "DNP3", "OPC UA", "EtherNet/IP"],
        },
        {
            "id": "water_analyzers_instruments",
            "parent_id": "water_ot_control",
            "label": "Analyzers, Sensors, and Instrumentation",
            "category": "safety",
            "description": "pH, turbidity, residual chlorine, flow, and level instrumentation that feed both control and safety decisions.",
        },
        {
            "id": "water_network_remote",
            "parent_id": None,
            "label": "Networking, Remote Access, and Telemetry",
            "category": "networking",
            "description": "Municipal IT/OT boundaries, VPNs, radio and cellular telemetry, and vendor pathways into the plant and remote assets.",
            "telemetry": ["Firewall logs", "VPN logs", "Radio link alarms", "Remote session history"],
        },
        {
            "id": "water_it_ot_boundary",
            "parent_id": "water_network_remote",
            "label": "Municipal IT / OT Boundary and Shared Services",
            "category": "networking",
            "description": "Connections between city business IT, domain services, remote support tooling, and plant operations systems.",
        },
        {
            "id": "water_remote_access_radio",
            "parent_id": "water_network_remote",
            "label": "Remote Access, Radio, and Cellular Telemetry",
            "category": "networking",
            "description": "Operational links used for remote pumps, reservoir telemetry, field maintenance, or emergency support.",
        },
        {
            "id": "water_quality_safety",
            "parent_id": None,
            "label": "Water Quality, Safeguards, and Compliance Controls",
            "category": "safety",
            "description": "Interlocks, alarm thresholds, lab workflows, and regulatory checks intended to prevent unsafe treatment output.",
            "attack_surfaces": ["Alarm thresholds", "Manual overrides", "Quality data entry", "Compliance workflows"],
        },
        {
            "id": "water_dosing_interlocks",
            "parent_id": "water_quality_safety",
            "label": "Dosing Interlocks, Limits, and Shutdown Logic",
            "category": "safety",
            "description": "Automated or operator-enforced safeguards restricting unsafe dosing or abnormal process conditions.",
        },
        {
            "id": "water_lims_reporting",
            "parent_id": "water_quality_safety",
            "label": "Laboratory, LIMS, and Regulatory Reporting",
            "category": "service",
            "description": "Quality-assurance and reporting systems used to verify safe operation and preserve compliance evidence.",
        },
        {
            "id": "water_monitoring_process",
            "parent_id": None,
            "label": "Monitoring, Maintenance, and Incident Response",
            "category": "monitoring",
            "description": "Historians, alarm review, maintenance windows, and emergency escalation paths that affect detection and recovery.",
            "telemetry": ["Historian trends", "Alarm journal", "Operator notes", "Maintenance tickets"],
        },
        {
            "id": "water_alarm_historian_review",
            "parent_id": "water_monitoring_process",
            "label": "Alarm Review, Historian Trends, and Operator Visibility",
            "category": "monitoring",
            "description": "Operational evidence used to separate equipment issues from misuse or covert setpoint manipulation.",
        },
        {
            "id": "water_maintenance_emergency",
            "parent_id": "water_monitoring_process",
            "label": "Maintenance Windows and Emergency Response",
            "category": "process",
            "description": "Planned work, bypass conditions, and emergency procedures that can create concealment or slow recovery.",
        },
    ],
}


TELECOMS_5G_CORE_CATALOG = {
    "id": "telecoms_5g_core",
    "name": "Telecoms 5G Core",
    "sector": "Telecommunications / 5G Core / Carrier Cloud",
    "description": (
        "Reference decomposition of a 5G core environment, including carrier operations, service-based core functions, "
        "cloud and orchestration layers, signalling and roaming edges, subscriber-data systems, charging and voice services, and assurance processes."
    ),
    "context_presets": ["telecoms_5g_core"],
    "nodes": [
        {
            "id": "core_people_roles",
            "parent_id": None,
            "label": "People, Carrier Operations, and Trusted Parties",
            "category": "people",
            "description": "Core-network operators, platform engineers, roaming teams, lawful-intercept staff, and vendor support paths.",
            "attack_surfaces": ["Privileged operations", "Inter-operator trust", "Emergency changes", "Managed service access"],
        },
        {
            "id": "core_noc_platform",
            "parent_id": "core_people_roles",
            "label": "Core NOC, Platform, and Security Teams",
            "category": "people",
            "description": "Staff operating subscriber services, cloud infrastructure, observability, and incident response for the carrier core.",
        },
        {
            "id": "roaming_interconnect_partners",
            "parent_id": "core_people_roles",
            "label": "Roaming, Interconnect, and Partner Operations",
            "category": "people",
            "description": "External carriers and partner teams exchanging signalling traffic, subscriber context, and operational trust.",
        },
        {
            "id": "core_oem_msp",
            "parent_id": "core_people_roles",
            "label": "OEMs, Cloud Vendors, and Managed Services",
            "category": "people",
            "description": "Suppliers maintaining CNFs, orchestration, subscriber databases, or edge transport components.",
            "management_interfaces": ["Vendor VPN", "Support jump hosts", "Automation tooling"],
        },
        {
            "id": "core_network_functions",
            "parent_id": None,
            "label": "5G Core Network Functions and Subscriber Services",
            "category": "ot",
            "description": "Service-based network functions, policy services, subscriber stores, and packet-core elements enabling mobile service.",
            "attack_surfaces": ["SBA APIs", "Service discovery", "Network function certificates", "Subscriber data access"],
        },
        {
            "id": "core_sba_functions",
            "parent_id": "core_network_functions",
            "label": "AMF, SMF, UPF, NRF, PCF, AUSF, and SBA Services",
            "category": "ot",
            "description": "Cloud-native core functions communicating over HTTP/2, REST, and service meshes within the 5G control and user plane.",
            "common_protocols": ["HTTP/2", "REST", "PFCP", "GTP-U"],
        },
        {
            "id": "core_policy_slice_charging",
            "parent_id": "core_network_functions",
            "label": "NSSF, PCF, CHF/OCS, and Policy or Charging Services",
            "category": "service",
            "description": "Network-slice, policy, charging, and quota-control services that decide traffic treatment, charging state, and subscriber experience.",
        },
        {
            "id": "core_user_plane_breakout",
            "parent_id": "core_network_functions",
            "label": "UPF Steering, Local Breakout, and Edge User Plane",
            "category": "ot",
            "description": "User-plane steering and breakout functions governing traffic anchoring, lawful routing, and low-latency edge service delivery.",
        },
        {
            "id": "core_subscriber_voice",
            "parent_id": "core_network_functions",
            "label": "Subscriber Data, IMS, Messaging, and Voice Services",
            "category": "service",
            "description": "Subscriber records, IMS elements, messaging, and voice-service components with high confidentiality and service impact.",
        },
        {
            "id": "core_udm_udr_hss_eir",
            "parent_id": "core_network_functions",
            "label": "UDM, UDR, HSS/HLR, EIR, and SIM Provisioning",
            "category": "service",
            "description": "Subscriber and device identity platforms storing provisioning state, IMEI policy, authentication context, and lifecycle information for mobile services.",
        },
        {
            "id": "core_ims_sbc_messaging",
            "parent_id": "core_network_functions",
            "label": "IMS CSCF, SBC, SMSC, RCS, and Voice or Messaging Platforms",
            "category": "service",
            "description": "Voice, messaging, and interconnect service stacks supporting SIP sessions, SMS, RCS, and subscriber-facing communications services.",
        },
        {
            "id": "core_cloud_management",
            "parent_id": None,
            "label": "Carrier Cloud, Orchestration, and Management Plane",
            "category": "it",
            "description": "NFVI, Kubernetes, OpenStack, CI/CD, secrets, and lifecycle tooling running or updating the carrier core.",
            "telemetry": ["Cluster audit logs", "Image registry events", "Deployment history", "Privilege escalations"],
        },
        {
            "id": "core_nfvi_k8s",
            "parent_id": "core_cloud_management",
            "label": "NFVI, Kubernetes, and Virtualisation Platforms",
            "category": "it",
            "description": "Underlying platform layers providing compute, storage, and networking to cloud-native network functions.",
            "example_technologies": ["Kubernetes", "OpenStack", "OpenShift", "VMware Telco Cloud"],
        },
        {
            "id": "core_timing_distribution",
            "parent_id": "core_cloud_management",
            "label": "ePRTC, PTP Grandmasters, Boundary Clocks, and Time Distribution",
            "category": "networking",
            "description": "Carrier timing appliances and distribution paths providing traceable time to cloud platforms, UPFs, charging systems, and RAN-facing services.",
            "common_protocols": ["PTP", "SyncE", "NTP"],
        },
        {
            "id": "core_ci_cd_secrets",
            "parent_id": "core_cloud_management",
            "label": "CI/CD, Images, and Secrets Management",
            "category": "it",
            "description": "Release pipelines, image registries, credential stores, and automation used to deploy or patch the core.",
        },
        {
            "id": "core_cnf_onboarding_gitops",
            "parent_id": "core_cloud_management",
            "label": "CNF Onboarding, GitOps, Helm, and Package Management",
            "category": "it",
            "description": "Lifecycle tooling used to onboard vendor packages, apply Helm charts, manage GitOps state, and push changes into production core functions.",
        },
        {
            "id": "core_service_mesh_pki",
            "parent_id": "core_cloud_management",
            "label": "Service Mesh, mTLS, and Network Function PKI",
            "category": "it",
            "description": "Certificate, mTLS, and service-mesh control layers that authenticate network functions and secure east-west communication.",
        },
        {
            "id": "core_oam_observability",
            "parent_id": "core_cloud_management",
            "label": "OAM, Element Managers, and Observability",
            "category": "it",
            "description": "Carrier tooling for provisioning, alarms, KPI analysis, and software rollouts across network functions.",
        },
        {
            "id": "core_oss_bss_subscriber_admin",
            "parent_id": "core_cloud_management",
            "label": "OSS, BSS, Subscriber Admin, and Provisioning Systems",
            "category": "it",
            "description": "Business and operational support systems used to provision subscribers, activate services, manage billing context, and coordinate carrier operations.",
        },
        {
            "id": "core_interconnect_edges",
            "parent_id": None,
            "label": "Interconnect, Signalling, and External Interfaces",
            "category": "networking",
            "description": "Roaming and peering edges, SBA exposure, API gateways, and signalling paths into or out of the carrier core.",
            "telemetry": ["Interconnect logs", "API gateway logs", "Diameter counters", "Roaming alarms"],
        },
        {
            "id": "core_ss7_diameter",
            "parent_id": "core_interconnect_edges",
            "label": "SS7, Diameter, and Roaming Interconnect",
            "category": "networking",
            "description": "Legacy and transitional signalling surfaces still carrying subscriber and mobility trust across operators.",
            "common_protocols": ["SS7", "Diameter", "SIP", "MAP/CAP"],
        },
        {
            "id": "core_sepp_ipx_roaming",
            "parent_id": "core_interconnect_edges",
            "label": "SEPP, IPX, and Roaming Security Functions",
            "category": "networking",
            "description": "Roaming security and inter-provider exchange services mediating signalling, policy, and subscriber context across external carrier boundaries.",
        },
        {
            "id": "core_sba_api_exposure",
            "parent_id": "core_interconnect_edges",
            "label": "SBA Exposure, API Gateways, and Service Mesh",
            "category": "networking",
            "description": "North-south and east-west exposure layers that govern authentication, discovery, and policy between network functions.",
        },
        {
            "id": "core_nef_scp_partner_apis",
            "parent_id": "core_interconnect_edges",
            "label": "NEF, SCP, Partner APIs, and Exposure Mediation",
            "category": "networking",
            "description": "Exposure and mediation layers that publish network capabilities, service discovery, and partner-facing APIs into controlled or semi-controlled external consumers.",
        },
        {
            "id": "core_sensitive_compliance",
            "parent_id": None,
            "label": "Sensitive Data, Identity, and Compliance Services",
            "category": "safety",
            "description": "Subscriber identity, key material, lawful intercept, and regulatory functions requiring elevated trust and controls.",
            "attack_surfaces": ["Authentication vectors", "PKI", "LI mediation access", "Subscriber database replication"],
        },
        {
            "id": "core_auth_keys_identity",
            "parent_id": "core_sensitive_compliance",
            "label": "Authentication Keys, Subscriber Identity, and PKI",
            "category": "safety",
            "description": "Stores and systems governing subscriber auth, certificate trust, and security associations across the core.",
        },
        {
            "id": "core_hsm_key_material",
            "parent_id": "core_sensitive_compliance",
            "label": "HSMs, Key Material, and Subscriber Trust Anchors",
            "category": "safety",
            "description": "Cryptographic modules and secret stores protecting signing material, subscriber authentication roots, and operator trust anchors.",
        },
        {
            "id": "core_lawful_intercept",
            "parent_id": "core_sensitive_compliance",
            "label": "Lawful Intercept, Compliance, and Sensitive Mediation",
            "category": "service",
            "description": "Highly sensitive mediation and warrant-handling functions whose compromise enables surveillance abuse or blind spots.",
        },
        {
            "id": "core_charging_cdr_mediation",
            "parent_id": "core_sensitive_compliance",
            "label": "Charging, CDR, Mediation, and Settlement Platforms",
            "category": "service",
            "description": "Billing and mediation services collecting usage records, correlating charging state, and supporting roaming settlement or customer-impact decisions.",
        },
        {
            "id": "core_monitoring_process",
            "parent_id": None,
            "label": "Monitoring, Assurance, and Change Process",
            "category": "monitoring",
            "description": "Fault management, performance assurance, release controls, and outage-response workflows shaping visibility and resilience.",
            "telemetry": ["Fault alarms", "Performance counters", "Tracing data", "Change records"],
        },
        {
            "id": "core_fault_perf_assurance",
            "parent_id": "core_monitoring_process",
            "label": "Fault, Performance, and Trace Assurance",
            "category": "monitoring",
            "description": "Alarm, KPI, and trace data used to detect abuse, service degradation, and anomalous network-function behaviour.",
        },
        {
            "id": "core_signalling_fraud_security",
            "parent_id": "core_monitoring_process",
            "label": "Signalling Firewalls, Fraud, and Abuse Detection",
            "category": "monitoring",
            "description": "Security analytics and signalling-control layers used to detect roaming abuse, SMS fraud, API misuse, and suspicious subscriber or interconnect behaviour.",
        },
        {
            "id": "core_timing_assurance",
            "parent_id": "core_monitoring_process",
            "label": "Timing Assurance, Holdover, and PNT Resilience",
            "category": "monitoring",
            "description": "Controls and analytics tracking GNSS loss, grandmaster failover, clock drift, holdover state, and downstream impact on charging, lawful intercept, and ordered event records.",
        },
        {
            "id": "core_change_release_incident",
            "parent_id": "core_monitoring_process",
            "label": "Change Control, Release Management, and Incident Response",
            "category": "process",
            "description": "Software rollout, rollback, emergency change, and outage-bridge processes that can conceal or accelerate compromise.",
        },
    ],
}


PORT_MARITIME_TERMINAL_CATALOG = {
    "id": "port_maritime_terminal",
    "name": "Port / Maritime Terminal",
    "sector": "Port Operations / Maritime Logistics",
    "description": (
        "Reference decomposition of a port or maritime terminal, including terminal operations, customs and logistics partners, "
        "cargo-handling OT, gate and yard systems, vessel-traffic dependencies, and recovery workflows."
    ),
    "context_presets": ["port_maritime_terminal"],
    "nodes": [
        {
            "id": "port_people_roles",
            "parent_id": None,
            "label": "People, Port Operations, and Trusted Parties",
            "category": "people",
            "description": "Terminal planners, customs teams, crane operators, truck interfaces, shipping lines, and vendors involved in cargo movement.",
            "attack_surfaces": ["Port passes", "Shift handovers", "Customs workflows", "Vendor remote support"],
        },
        {
            "id": "port_terminal_ops",
            "parent_id": "port_people_roles",
            "label": "Terminal Operations, Planning, and Dispatch",
            "category": "people",
            "description": "Teams coordinating berth plans, yard moves, crane schedules, and exception handling across the terminal.",
        },
        {
            "id": "port_customs_logistics_partners",
            "parent_id": "port_people_roles",
            "label": "Customs, Trucking, Shipping Lines, and Logistics Partners",
            "category": "people",
            "description": "External organisations exchanging manifests, gate requests, and cargo instructions with the terminal.",
        },
        {
            "id": "port_oem_service_vendors",
            "parent_id": "port_people_roles",
            "label": "OEM Service Teams and Yard Equipment Vendors",
            "category": "people",
            "description": "Third parties maintaining cranes, gate automation, vessel systems, networking, or industrial wireless platforms.",
        },
        {
            "id": "port_physical_terminal",
            "parent_id": None,
            "label": "Physical Terminal, Yard, and Access Control",
            "category": "physical",
            "description": "Perimeter controls, berth areas, yards, gates, equipment corridors, and access paths into operational technology or cargo records.",
            "telemetry": ["Gate events", "CCTV", "Badge logs", "Vehicle movement records"],
        },
        {
            "id": "port_gates_yard_perimeter",
            "parent_id": "port_physical_terminal",
            "label": "Gates, Yard Lanes, and Perimeter Access",
            "category": "physical",
            "description": "Truck gates, pedestrian entry points, container stacks, and restricted operational zones.",
        },
        {
            "id": "port_cranes_berths_power",
            "parent_id": "port_physical_terminal",
            "label": "Cranes, Berths, and Power or Fuel Support Areas",
            "category": "physical",
            "description": "Ship-to-shore cranes, yard cranes, berth services, and supporting utilities with direct safety implications.",
        },
        {
            "id": "port_it_business",
            "parent_id": None,
            "label": "Terminal IT, TOS, and Logistics Platforms",
            "category": "it",
            "description": "Terminal operating systems, scheduling platforms, gate applications, customs integrations, and back-office services.",
            "attack_surfaces": ["TOS credentials", "Manifest imports", "API integrations", "Ransomware paths"],
        },
        {
            "id": "port_tos_databases",
            "parent_id": "port_it_business",
            "label": "Terminal Operating System, Planning, and Databases",
            "category": "it",
            "description": "Core applications handling container records, berth allocation, yard moves, and crane job sequencing.",
        },
        {
            "id": "port_customs_gate_apps",
            "parent_id": "port_it_business",
            "label": "Customs, Gate, and Partner-Facing Applications",
            "category": "service",
            "description": "Business systems exchanging manifests, truck appointments, inspection status, and port community data.",
        },
        {
            "id": "port_ot_control",
            "parent_id": None,
            "label": "Cargo-Handling OT and Automation",
            "category": "ot",
            "description": "PLC-controlled cranes, yard automation, weighbridges, fuel systems, and other industrial assets moving cargo through the terminal.",
            "attack_surfaces": ["Engineering laptops", "PLC logic uploads", "Safety bypasses", "Industrial HMIs"],
        },
        {
            "id": "port_crane_plc_safety",
            "parent_id": "port_ot_control",
            "label": "Crane PLCs, Drives, and Safety Systems",
            "category": "ot",
            "description": "Automation and safety layers controlling crane motion, anti-collision, and interlocks.",
            "common_protocols": ["PROFINET", "Modbus", "OPC UA", "EtherNet/IP"],
        },
        {
            "id": "port_yard_automation",
            "parent_id": "port_ot_control",
            "label": "Yard Automation, AGVs, and Field Equipment",
            "category": "ot",
            "description": "Automated guided vehicles, yard tractors, stackers, and field-control systems coordinating container movement.",
        },
        {
            "id": "port_network_vessel",
            "parent_id": None,
            "label": "Networking, Wireless, and Vessel Interfaces",
            "category": "networking",
            "description": "Industrial wireless, terminal fibre, vessel-traffic systems, AIS, and vendor support links into port operations.",
            "telemetry": ["Wireless controller logs", "AIS/VTS events", "Firewall logs", "Remote-access sessions"],
        },
        {
            "id": "port_wireless_radio",
            "parent_id": "port_network_vessel",
            "label": "Industrial Wireless, Radio, and Mobile Networks",
            "category": "networking",
            "description": "Wi-Fi, private LTE, handheld radios, and mobile data services supporting cranes, vehicles, and field teams.",
        },
        {
            "id": "port_vts_ais_ship_shore",
            "parent_id": "port_network_vessel",
            "label": "VTS, AIS, and Ship-to-Shore Interfaces",
            "category": "networking",
            "description": "Maritime coordination systems linking vessel movement, berth status, and navigation support into terminal operations.",
        },
        {
            "id": "port_vendor_remote",
            "parent_id": "port_network_vessel",
            "label": "Vendor Remote Access and Third-Party Support Paths",
            "category": "networking",
            "description": "Trusted support channels into cranes, gate systems, TOS infrastructure, or industrial networking components.",
        },
        {
            "id": "port_monitoring_recovery",
            "parent_id": None,
            "label": "Monitoring, Safety, and Recovery Process",
            "category": "monitoring",
            "description": "SOC visibility, operational alarms, manual fallback procedures, and business-continuity workflows affecting outage handling.",
            "telemetry": ["SOC alerts", "Equipment alarms", "Gate queue metrics", "Incident logs"],
        },
        {
            "id": "port_cctv_siem_alarms",
            "parent_id": "port_monitoring_recovery",
            "label": "CCTV, SIEM, and Operational Alarming",
            "category": "monitoring",
            "description": "Signals used to correlate cyber events with gate anomalies, crane failures, or suspicious cargo movement.",
        },
        {
            "id": "port_manual_fallback_bcp",
            "parent_id": "port_monitoring_recovery",
            "label": "Manual Fallback, Business Continuity, and Incident Response",
            "category": "process",
            "description": "Paper workflows, degraded-mode operations, and restoration plans used when automated systems fail or are distrusted.",
        },
    ],
}


OIL_GAS_PIPELINE_CATALOG = {
    "id": "oil_gas_pipeline",
    "name": "Oil and Gas Pipeline / Compressor Station",
    "sector": "Oil & Gas / Midstream / Pipeline",
    "description": (
        "Reference decomposition of an oil or gas pipeline environment, including control-room operations, remote compressor or valve sites, "
        "SCADA and ESD systems, field communications, integrity safeguards, and emergency response dependencies."
    ),
    "context_presets": ["oil_gas_pipeline"],
    "nodes": [
        {
            "id": "pipeline_people_roles",
            "parent_id": None,
            "label": "People, Pipeline Control, and Trusted Parties",
            "category": "people",
            "description": "Pipeline controllers, field technicians, midstream engineers, contractors, and OEMs involved in access and incident handling.",
            "attack_surfaces": ["Control-room approvals", "Field callouts", "Vendor trust", "Maintenance windows"],
        },
        {
            "id": "pipeline_controllers_field",
            "parent_id": "pipeline_people_roles",
            "label": "Controllers, Dispatch, and Field Technicians",
            "category": "people",
            "description": "Operations staff managing flow setpoints, compressor performance, valve states, and emergency escalation.",
        },
        {
            "id": "pipeline_oem_contractors",
            "parent_id": "pipeline_people_roles",
            "label": "OEM Support, Contractors, and Integrators",
            "category": "people",
            "description": "Third parties maintaining compressor controls, ESD systems, metering skids, and field communications.",
            "management_interfaces": ["Vendor VPN", "Field laptops", "Temporary engineering access"],
        },
        {
            "id": "pipeline_physical_sites",
            "parent_id": None,
            "label": "Physical Sites, Remote Assets, and Field Access",
            "category": "physical",
            "description": "Compressor stations, meter stations, block-valve sites, cabinets, utility power, and remote rights-of-way.",
            "telemetry": ["Fence alarms", "Cabinet-door events", "CCTV", "Remote-site access records"],
        },
        {
            "id": "pipeline_compressor_meter_sites",
            "parent_id": "pipeline_physical_sites",
            "label": "Compressor, Metering, and Valve Sites",
            "category": "physical",
            "description": "Operational sites where process control, safety systems, and custody-transfer functions converge.",
        },
        {
            "id": "pipeline_row_power_aux",
            "parent_id": "pipeline_physical_sites",
            "label": "Remote Cabinets, Utility Power, and Auxiliary Systems",
            "category": "service",
            "description": "Remote cabinets, backup power, local fuel or gas support, and environmental protections for unattended sites.",
        },
        {
            "id": "pipeline_scada_control",
            "parent_id": None,
            "label": "SCADA, PLCs, and Process Control",
            "category": "ot",
            "description": "SCADA masters, compressor controls, PLCs, RTUs, ESD logic, and historians governing flow and shutdown behaviour.",
            "attack_surfaces": ["SCADA HMIs", "Logic downloads", "Remote telemetry", "Safety bypasses"],
        },
        {
            "id": "pipeline_scada_historians",
            "parent_id": "pipeline_scada_control",
            "label": "SCADA Masters, HMIs, and Historians",
            "category": "ot",
            "description": "Central control-room systems monitoring pipeline state, issuing commands, and preserving operational history.",
        },
        {
            "id": "pipeline_plc_rtu_esd",
            "parent_id": "pipeline_scada_control",
            "label": "PLCs, RTUs, Compressor Control, and ESD Systems",
            "category": "safety",
            "description": "Field control and shutdown systems responsible for pressure control, station protection, and remote actuation.",
            "common_protocols": ["Modbus", "DNP3", "IEC 60870-5-104", "OPC UA"],
        },
        {
            "id": "pipeline_network_remote",
            "parent_id": None,
            "label": "Field Communications, Remote Access, and Telemetry",
            "category": "networking",
            "description": "Leased lines, microwave, satellite, radio, cellular backhaul, and support channels linking remote assets to the control centre.",
            "telemetry": ["Carrier alarms", "VPN logs", "Radio telemetry", "Firewall events"],
        },
        {
            "id": "pipeline_backhaul_radio",
            "parent_id": "pipeline_network_remote",
            "label": "Leased Line, Microwave, Radio, Cellular, and Satellite Backhaul",
            "category": "networking",
            "description": "Long-distance communications paths carrying supervisory data, alarms, and command traffic between distributed sites.",
        },
        {
            "id": "pipeline_serial_gateways",
            "parent_id": "pipeline_network_remote",
            "label": "Serial Protocol Gateways and Field Network Aggregation",
            "category": "networking",
            "description": "Legacy and mixed transport layers bridging RTUs, analyzers, compressor packages, and remote valve controls.",
        },
        {
            "id": "pipeline_vendor_remote",
            "parent_id": "pipeline_network_remote",
            "label": "Vendor Remote Support and Temporary Engineering Access",
            "category": "networking",
            "description": "Trusted remote pathways used during maintenance, troubleshooting, and emergency support.",
        },
        {
            "id": "pipeline_safety_integrity",
            "parent_id": None,
            "label": "Safety, Metering, and Process Integrity",
            "category": "safety",
            "description": "Leak detection, pressure protection, shutdown interlocks, and measurement systems used to keep the pipeline safe and trusted.",
            "attack_surfaces": ["Alarm thresholds", "Trip settings", "Manual overrides", "Custody-transfer trust"],
        },
        {
            "id": "pipeline_leak_pressure",
            "parent_id": "pipeline_safety_integrity",
            "label": "Leak Detection, Pressure Protection, and Shutdown Logic",
            "category": "safety",
            "description": "Protective functions designed to isolate faults, contain releases, and avoid unsafe operating states.",
        },
        {
            "id": "pipeline_metering_quality",
            "parent_id": "pipeline_safety_integrity",
            "label": "Metering, Flow Assurance, and Product Quality Systems",
            "category": "service",
            "description": "Measurement and quality services that influence billing, dispatch decisions, and process confidence.",
        },
        {
            "id": "pipeline_monitoring_process",
            "parent_id": None,
            "label": "Monitoring, Maintenance, and Emergency Response",
            "category": "monitoring",
            "description": "Alarm review, historian analysis, pigging or outage work, and emergency-response procedures shaping detection and restoration.",
            "telemetry": ["Alarm journals", "Historian trends", "Batch records", "Emergency logs"],
        },
        {
            "id": "pipeline_alarm_historian",
            "parent_id": "pipeline_monitoring_process",
            "label": "Alarm Management, Historian Trends, and Operational Visibility",
            "category": "monitoring",
            "description": "Signals used to distinguish equipment faults, process drift, and intentional manipulation across dispersed sites.",
        },
        {
            "id": "pipeline_maintenance_emergency",
            "parent_id": "pipeline_monitoring_process",
            "label": "Maintenance, Pigging, and Emergency Shutdown or Recovery",
            "category": "process",
            "description": "Operational workflows that can create temporary trust exceptions, degraded monitoring, or recovery bottlenecks.",
        },
    ],
}
