"""Bundled environment catalog data for planning-first decomposition."""

from __future__ import annotations

from .environment_catalog_additions import (
    ELECTRICAL_SUBSTATION_CATALOG,
    OIL_GAS_PIPELINE_CATALOG,
    PORT_MARITIME_TERMINAL_CATALOG,
    TELECOMS_5G_CORE_CATALOG,
    WATER_TREATMENT_PLANT_CATALOG,
)
from .environment_catalog_additions_more import (
    AIRPORT_CATALOG,
    DEFENCE_MANUFACTURING_PLANT_CATALOG,
    DRILLING_RIG_CATALOG,
    EV_CHARGING_NETWORK_CATALOG,
    LNG_TERMINAL_CATALOG,
    MANUFACTURING_FACILITY_CATALOG,
    MILITARY_HEADQUARTERS_CATALOG,
    OIL_REFINERY_CATALOG,
    PHARMA_MANUFACTURING_PLANT_CATALOG,
    SATELLITE_GROUND_STATION_CATALOG,
    SHIPYARD_NAVAL_BASE_CATALOG,
)


DATA_CENTRE_CATALOG = {
    "id": "data_centre",
    "name": "Data Centre",
    "sector": "Facility / Colocation / Hosting",
    "description": (
        "Reference decomposition of a modern data centre, including people, facility, IT management plane, "
        "networking, BMS/power/cooling, and operational process dependencies."
    ),
    "context_presets": ["data_centre"],
    "nodes": [
        {
            "id": "people_roles",
            "parent_id": None,
            "label": "People and Trusted Roles",
            "category": "people",
            "description": (
                "Human access paths that can create or remove friction for an operator, including privileged IT teams, "
                "remote hands, facilities staff, and third-party field engineers."
            ),
            "attack_surfaces": ["Privileged actions", "Insider access", "Social engineering", "Maintenance workflows"],
            "telemetry": ["Badge logs", "Ticketing records", "Change windows", "Remote hands job history"],
        },
        {
            "id": "operators_engineers",
            "parent_id": "people_roles",
            "label": "Operators and Platform Engineers",
            "category": "people",
            "description": "Administrators running hypervisors, storage, orchestration, backup, identity, and OOB management platforms.",
            "management_interfaces": ["vCenter", "Hyper-V", "VMware ESXi", "Backup consoles"],
            "dependencies": ["MFA", "Jump hosts", "Privileged access management"],
        },
        {
            "id": "remote_hands_contractors",
            "parent_id": "people_roles",
            "label": "Remote Hands and Contractors",
            "category": "people",
            "description": "Outsourced staff with rack access, console tasks, media handling duties, or escort-based maintenance permissions.",
            "attack_surfaces": ["Work orders", "Phone verification", "Temporary badges", "Console access"],
            "dependencies": ["Escorts", "Ticket validation", "Customer approval workflows"],
        },
        {
            "id": "vendors_field_service",
            "parent_id": "people_roles",
            "label": "Vendors and Field Service",
            "category": "people",
            "description": "Hardware, BMS, generator, UPS, HVAC, and network-carrier vendors who may hold trusted remote or on-site support paths.",
            "management_interfaces": ["Vendor VPN", "Field laptops", "Support portals"],
            "dependencies": ["Maintenance windows", "Firmware supply chain", "Remote diagnostics"],
        },
        {
            "id": "physical_facility",
            "parent_id": None,
            "label": "Physical Infrastructure and Facility Access",
            "category": "physical",
            "description": (
                "The site perimeter, loading and staging areas, cages, racks, cabling, media handling, and any physical path "
                "into equipment or management interfaces."
            ),
            "attack_surfaces": ["Perimeter", "Loading bays", "Cages", "Rack access", "Console ports"],
            "telemetry": ["CCTV", "Door access events", "Visitor management", "Asset movement logs"],
        },
        {
            "id": "perimeter_loading",
            "parent_id": "physical_facility",
            "label": "Perimeter and Loading Areas",
            "category": "physical",
            "description": "Vehicle gates, receiving areas, dock doors, and temporary staging spaces where hardware, media, and contractor activity converge.",
            "dependencies": ["Guard force", "Visitor procedures", "Delivery validation"],
        },
        {
            "id": "cages_racks_console",
            "parent_id": "physical_facility",
            "label": "Cages, Racks, and Console Access",
            "category": "physical",
            "description": "Cabinet locks, KVM drawers, crash carts, serial consoles, removable media paths, and exposed service ports.",
            "management_interfaces": ["KVM over IP", "Serial console servers", "BMC/IPMI"],
            "attack_surfaces": ["USB media", "Serial ports", "Direct cabling changes"],
        },
        {
            "id": "media_spares_disposal",
            "parent_id": "physical_facility",
            "label": "Media, Spares, and Disposal Workflows",
            "category": "physical",
            "description": "Hard drive swaps, failed component returns, spare-device staging, and destruction procedures that affect data remanence and hardware trust.",
            "dependencies": ["Chain of custody", "Sanitisation process", "RMA workflows"],
        },
        {
            "id": "it_management",
            "parent_id": None,
            "label": "Information Technology and Management Plane",
            "category": "it",
            "description": "Virtualisation, compute, storage, identity, backup, orchestration, and out-of-band platforms that expose high-value administrative control.",
            "attack_surfaces": ["Management APIs", "Admin consoles", "Directory services", "Backup systems"],
            "telemetry": ["Admin audit logs", "EDR", "Identity logs", "Configuration history"],
        },
        {
            "id": "virtualization_compute",
            "parent_id": "it_management",
            "label": "Virtualisation and Compute Control",
            "category": "it",
            "description": "Hypervisors, cluster managers, bare-metal automation, and workload schedulers controlling hosted services and customer infrastructure.",
            "management_interfaces": ["vCenter", "OpenStack", "VMware APIs", "IPMI tooling"],
            "example_technologies": ["VMware ESXi", "Hyper-V", "Kubernetes", "OpenStack"],
        },
        {
            "id": "identity_privileged_access",
            "parent_id": "it_management",
            "label": "Identity and Privileged Access",
            "category": "it",
            "description": "Directory services, PAM, MFA, bastions, and break-glass paths governing who can touch the estate.",
            "management_interfaces": ["Active Directory", "Entra ID", "PAM vaults", "Bastion hosts"],
            "dependencies": ["Credential lifecycle", "Service accounts", "Federation"],
        },
        {
            "id": "storage_backup_recovery",
            "parent_id": "it_management",
            "label": "Storage, Backup, and Recovery",
            "category": "storage",
            "description": "SAN/NAS fabrics, snapshot platforms, backup servers, replication, and disaster-recovery orchestration that affect resilience and data access.",
            "example_technologies": ["NetApp", "Pure Storage", "Veeam", "Commvault"],
            "dependencies": ["Replication links", "Key management", "Restore testing"],
        },
        {
            "id": "oob_dcim",
            "parent_id": "it_management",
            "label": "Out-of-Band and DCIM Management",
            "category": "it",
            "description": "BMC/IPMI, console aggregation, DCIM, inventory, and asset-control tooling that can bridge physical and logical control.",
            "management_interfaces": ["iDRAC", "iLO", "Redfish", "DCIM portals"],
            "attack_surfaces": ["OOB networks", "Default creds", "Firmware trust"],
        },
        {
            "id": "networking_remote_access",
            "parent_id": None,
            "label": "Networking, Carriers, and Remote Access",
            "category": "networking",
            "description": "Core switching, routing, firewalls, remote-admin paths, carrier handoffs, and cross-connect dependencies.",
            "attack_surfaces": ["VPN", "Jump hosts", "Management VLANs", "Carrier circuits"],
            "telemetry": ["NetFlow", "Firewall logs", "VPN auth logs", "Switch configuration history"],
        },
        {
            "id": "core_switching_routing",
            "parent_id": "networking_remote_access",
            "label": "Core Switching and Routing",
            "category": "networking",
            "description": "Spine-leaf, distribution, border, and management switching layers controlling east-west and north-south movement.",
            "common_protocols": ["BGP", "OSPF", "VRRP", "802.1X"],
            "example_technologies": ["Cisco Nexus", "Arista EOS", "Juniper MX"],
        },
        {
            "id": "firewalls_vpn_jump",
            "parent_id": "networking_remote_access",
            "label": "Firewalls, VPN, and Jump Hosts",
            "category": "networking",
            "description": "Security edge controls and privileged remote-access brokers used by operations teams and vendors.",
            "management_interfaces": ["SSL VPN", "RDP bastions", "SSH jump hosts"],
            "dependencies": ["MFA", "Conditional access", "Session recording"],
        },
        {
            "id": "cross_connects_carriers",
            "parent_id": "networking_remote_access",
            "label": "Cross-Connects and Carrier Dependencies",
            "category": "networking",
            "description": "Interconnects with customers, carriers, IXs, and managed network providers that affect ingress, egress, and shared trust.",
            "dependencies": ["Carrier tickets", "Meet-me rooms", "Patch panels"],
        },
        {
            "id": "bms_power_cooling",
            "parent_id": None,
            "label": "OT / BMS / Power / Cooling",
            "category": "ot",
            "description": "Facility-control systems supporting HVAC, chillers, UPS, generators, PDUs, sensors, and fire/life safety systems.",
            "attack_surfaces": ["BMS portals", "Serial gateways", "Vendor remote support", "Field controllers"],
            "telemetry": ["BMS alarms", "Generator events", "Power quality logs", "Environmental sensor history"],
        },
        {
            "id": "bms_dcim_sensors",
            "parent_id": "bms_power_cooling",
            "label": "BMS, DCIM, and Environmental Sensors",
            "category": "ot",
            "description": "Monitoring and control for environmental conditions, occupancy, access, and facility workflows.",
            "common_protocols": ["BACnet/IP", "Modbus TCP", "SNMP"],
            "example_technologies": ["Niagara", "EcoStruxure", "Schneider DCIM"],
        },
        {
            "id": "hvac_chillers",
            "parent_id": "bms_power_cooling",
            "label": "HVAC, CRAH/CRAC, and Chillers",
            "category": "ot",
            "description": "Cooling plant equipment whose disruption can force protective shutdowns or create cascading service impact.",
            "dependencies": ["Sensor calibration", "Control loops", "Vendor maintenance paths"],
        },
        {
            "id": "ups_pdu_generators",
            "parent_id": "bms_power_cooling",
            "label": "UPS, PDU, Transfer, and Generator Chain",
            "category": "ot",
            "description": "Electrical resilience stack covering rectification, UPS, static transfer, switchgear, PDUs, and backup generation.",
            "common_protocols": ["Modbus", "DNP3", "SNMP"],
            "dependencies": ["Fuel contracts", "Load shedding", "Breaker coordination"],
        },
        {
            "id": "monitoring_process",
            "parent_id": None,
            "label": "Monitoring, Detection, and Process Weaknesses",
            "category": "monitoring",
            "description": "Observability, security tooling, change control, failover practice, and incident-response workflows that shape detection and recovery.",
            "attack_surfaces": ["Blind spots", "Maintenance windows", "Unmonitored OOB paths"],
            "telemetry": ["SIEM", "NMS", "Runbooks", "Maintenance approvals"],
        },
        {
            "id": "siem_nms_soc",
            "parent_id": "monitoring_process",
            "label": "SIEM, NMS, and Security Operations",
            "category": "monitoring",
            "description": "Centralised logging, alert triage, network monitoring, and EDR coverage across IT and facility systems.",
        },
        {
            "id": "change_failover_response",
            "parent_id": "monitoring_process",
            "label": "Change Control, Failover, and Incident Response",
            "category": "process",
            "description": "Operational procedures that influence whether malicious activity blends into approved work or causes chaotic recovery.",
        },
    ],
}


TELECOMS_BASE_STATION_CATALOG = {
    "id": "telecoms_base_station",
    "name": "Telecoms Base Station",
    "sector": "Telecommunications / RAN",
    "description": (
        "Reference decomposition of a cellular base station site, including RAN equipment, transport, OAM, power, "
        "physical site controls, and field operations."
    ),
    "context_presets": ["telecoms_base_station"],
    "nodes": [
        {
            "id": "site_people_roles",
            "parent_id": None,
            "label": "People, Site Operations, and Trusted Parties",
            "category": "people",
            "description": "Roles involved in tower access, radio maintenance, transport provisioning, and remote network operations.",
            "attack_surfaces": ["Remote support", "Field-service workflows", "Site access approvals"],
        },
        {
            "id": "ran_noc_soc",
            "parent_id": "site_people_roles",
            "label": "RAN, NOC, and SOC Teams",
            "category": "people",
            "description": "Carrier staff operating element managers, fault systems, and performance tooling for the site.",
        },
        {
            "id": "riggers_field_engineers",
            "parent_id": "site_people_roles",
            "label": "Riggers and Field Engineers",
            "category": "people",
            "description": "Teams with physical reach into towers, shelters, cabinets, antennas, and cabling.",
        },
        {
            "id": "managed_service_vendors",
            "parent_id": "site_people_roles",
            "label": "Managed Service Providers and Vendors",
            "category": "people",
            "description": "OEM and outsourced operators maintaining radio firmware, OAM systems, batteries, generators, or microwave backhaul.",
            "management_interfaces": ["Vendor VPN", "OSS tools", "Field laptops"],
        },
        {
            "id": "physical_radio_site",
            "parent_id": None,
            "label": "Physical Site, Tower, and Shelter",
            "category": "physical",
            "description": "Compound, mast, shelter, cabinets, cabling, and access-control systems protecting the site.",
            "telemetry": ["Fence alarms", "Door contacts", "CCTV", "Site access events"],
        },
        {
            "id": "compound_shelter_cabinets",
            "parent_id": "physical_radio_site",
            "label": "Compound, Shelter, and Cabinets",
            "category": "physical",
            "description": "Locks, cabinet doors, power shelves, patch panels, and indoor equipment enclosures.",
        },
        {
            "id": "antennas_rru_feedlines",
            "parent_id": "physical_radio_site",
            "label": "Antennas, RRUs, and Feedline Paths",
            "category": "physical",
            "description": "Radio heads, antennas, combiners, cabling, and timing elements mounted on the mast or rooftop.",
        },
        {
            "id": "ran_equipment",
            "parent_id": None,
            "label": "Radio Access Network Equipment",
            "category": "ot",
            "description": "Baseband, distributed units, centralised units, radio heads, and timing components controlling service on the cell.",
            "attack_surfaces": ["Element managers", "Firmware updates", "Serial maintenance ports"],
        },
        {
            "id": "baseband_du_cu",
            "parent_id": "ran_equipment",
            "label": "Baseband, DU, and CU Functions",
            "category": "ot",
            "description": "Processing platforms hosting gNodeB/eNodeB control and user-plane functions.",
            "common_protocols": ["eCPRI", "S1", "X2", "F1", "NG"],
            "example_technologies": ["Ericsson", "Nokia AirScale", "Huawei", "Open RAN DU/CU"],
        },
        {
            "id": "timing_sync",
            "parent_id": "ran_equipment",
            "label": "Timing and Synchronisation",
            "category": "networking",
            "description": "GNSS, PTP, SyncE, and timing-distribution elements whose degradation impacts service and lawful operation.",
            "common_protocols": ["PTP", "SyncE", "NTP"],
        },
        {
            "id": "transport_networking",
            "parent_id": None,
            "label": "Transport, Networking, and OAM",
            "category": "networking",
            "description": "Microwave/fibre backhaul, routers, switches, firewalls, and OSS/OAM systems linking the site into the wider carrier network.",
            "telemetry": ["Transport alarms", "Router logs", "Path performance", "Configuration events"],
        },
        {
            "id": "microwave_fibre_backhaul",
            "parent_id": "transport_networking",
            "label": "Microwave and Fibre Backhaul",
            "category": "networking",
            "description": "Backhaul paths, aggregation handoffs, and fronthaul dependencies to the core or regional transport network.",
        },
        {
            "id": "site_routers_switches",
            "parent_id": "transport_networking",
            "label": "Site Routers, Switches, and Security Edge",
            "category": "networking",
            "description": "Local IP transport, management networks, and segmentation controls at the site.",
            "example_technologies": ["Cisco", "Juniper", "Nokia 7705", "MikroTik"],
        },
        {
            "id": "oam_element_managers",
            "parent_id": "transport_networking",
            "label": "Element Managers and OAM Systems",
            "category": "it",
            "description": "Centralised carrier tooling for provisioning, alarm handling, software rollout, and site diagnostics.",
            "management_interfaces": ["OSS/BSS", "EMS", "Northbound APIs", "Remote shells"],
        },
        {
            "id": "site_power_support",
            "parent_id": None,
            "label": "Power, Environmental, and Ancillary Systems",
            "category": "ot",
            "description": "Rectifiers, batteries, generators, HVAC, and site-support systems required to keep the cell online.",
            "attack_surfaces": ["Power controllers", "Remote telemetry", "Generator service paths"],
        },
        {
            "id": "rectifiers_batteries_generators",
            "parent_id": "site_power_support",
            "label": "Rectifiers, Batteries, and Generators",
            "category": "ot",
            "description": "DC power chain, autonomy systems, and backup generation sustaining the station during utility loss.",
        },
        {
            "id": "hvac_access_fire",
            "parent_id": "site_power_support",
            "label": "HVAC, Access Control, and Fire Systems",
            "category": "bms",
            "description": "Shelter temperature control, access alarms, and life-safety systems often maintained through separate vendors.",
        },
        {
            "id": "monitoring_process_telecom",
            "parent_id": None,
            "label": "Monitoring, Alarms, and Operational Process",
            "category": "monitoring",
            "description": "Alarm correlation, outage handling, maintenance windows, and emergency restoration procedures affecting service disruption and detection.",
            "telemetry": ["Alarm manager", "Ticketing", "Outage bridge logs", "Performance baselines"],
        },
        {
            "id": "telemetry_alarming",
            "parent_id": "monitoring_process_telecom",
            "label": "Telemetry and Alarming",
            "category": "monitoring",
            "description": "Fault, performance, and environmental monitoring that provides early signals of compromise or sabotage.",
        },
        {
            "id": "maintenance_restoration",
            "parent_id": "monitoring_process_telecom",
            "label": "Maintenance and Restoration Workflows",
            "category": "process",
            "description": "Planned work, software rollout, tower climbs, emergency dispatch, and recovery sequencing.",
        },
    ],
}


POWER_STATION_CATALOG = {
    "id": "power_station",
    "name": "Power Station",
    "sector": "Generation / Utility",
    "description": (
        "Reference decomposition of a conventional power station, including plant operations, DCS/PLC layers, protection, "
        "plant networking, enterprise IT, and safety/recovery dependencies."
    ),
    "context_presets": ["power_station"],
    "nodes": [
        {
            "id": "plant_people_roles",
            "parent_id": None,
            "label": "People, Operations, and Trusted Parties",
            "category": "people",
            "description": "Control-room operators, engineers, outage teams, OEMs, and remote support providers who shape both access and recovery.",
            "attack_surfaces": ["Engineering workflows", "Vendor trust", "Shift handover", "Maintenance approvals"],
        },
        {
            "id": "control_room_engineers",
            "parent_id": "plant_people_roles",
            "label": "Control Room and Plant Engineers",
            "category": "people",
            "description": "Operational staff managing plant state, setpoints, trips, and abnormal event handling.",
        },
        {
            "id": "outage_vendors_contractors",
            "parent_id": "plant_people_roles",
            "label": "Outage Vendors and Contractors",
            "category": "people",
            "description": "Short-term maintenance teams with broad temporary access during refit and planned outages.",
        },
        {
            "id": "plant_physical",
            "parent_id": None,
            "label": "Physical Plant and Balance of Plant",
            "category": "physical",
            "description": "Generation equipment, auxiliaries, switchgear, fuel/water handling, and physical access into control cabinets and engineering stations.",
            "telemetry": ["Perimeter alarms", "Equipment trips", "Plant cameras", "Work permits"],
        },
        {
            "id": "turbines_boilers_auxiliaries",
            "parent_id": "plant_physical",
            "label": "Turbines, Boilers, and Auxiliaries",
            "category": "physical",
            "description": "Core plant equipment and support subsystems whose manipulation causes process disruption or physical damage.",
        },
        {
            "id": "switchgear_relays",
            "parent_id": "plant_physical",
            "label": "Switchgear, Transformers, and Relay Panels",
            "category": "safety",
            "description": "Electrical plant assets where protection and control converge, including breaker operation and synchronisation.",
        },
        {
            "id": "ot_control",
            "parent_id": None,
            "label": "OT Control Systems",
            "category": "ot",
            "description": "DCS, PLCs, RTUs, HMIs, historians, and engineering workstations running the generation process.",
            "attack_surfaces": ["Engineering stations", "Control network", "Firmware updates", "Removable media"],
        },
        {
            "id": "dcs_hmi_eng",
            "parent_id": "ot_control",
            "label": "DCS, HMI, and Engineering Workstations",
            "category": "ot",
            "description": "Supervisory and engineering layers used to configure, monitor, and modify process logic.",
            "example_technologies": ["Honeywell Experion", "Yokogawa CENTUM", "GE Mark VIe", "Siemens SPPA-T3000"],
        },
        {
            "id": "plc_rtu_historians",
            "parent_id": "ot_control",
            "label": "PLCs, RTUs, and Historians",
            "category": "ot",
            "description": "Process-control endpoints and data-aggregation layers controlling field equipment and exposing operational history.",
            "common_protocols": ["Modbus", "DNP3", "IEC 61850", "OPC UA"],
        },
        {
            "id": "it_business_systems",
            "parent_id": None,
            "label": "IT Enterprise and Support Systems",
            "category": "it",
            "description": "Business IT, documentation, ERP, maintenance, historian access, and identity services bridging plant and enterprise needs.",
            "attack_surfaces": ["AD", "Email", "Vendor portals", "Patch servers"],
        },
        {
            "id": "enterprise_identity_email",
            "parent_id": "it_business_systems",
            "label": "Enterprise Identity, Email, and Collaboration",
            "category": "it",
            "description": "Corporate identity and user workflow systems that often provide the first foothold into plant-adjacent environments.",
        },
        {
            "id": "maintenance_lims_docs",
            "parent_id": "it_business_systems",
            "label": "Maintenance, LIMS, and Documentation Systems",
            "category": "service",
            "description": "CMMS/EAM, laboratory systems, document control, and planning tools with operational significance.",
        },
        {
            "id": "network_remote_access_plant",
            "parent_id": None,
            "label": "Plant Networking and Remote Access",
            "category": "networking",
            "description": "Plant DMZs, serial gateways, firewalls, vendor support links, and segmentation between corporate IT and OT networks.",
            "telemetry": ["Firewall events", "Remote access logs", "Network taps", "Switch port changes"],
        },
        {
            "id": "plant_dmz_vendors",
            "parent_id": "network_remote_access_plant",
            "label": "Plant DMZ and Vendor Support Paths",
            "category": "networking",
            "description": "Controlled or semi-controlled interconnects used for patching, monitoring, and external support.",
        },
        {
            "id": "serial_process_networks",
            "parent_id": "network_remote_access_plant",
            "label": "Process Networks and Serial Gateways",
            "category": "networking",
            "description": "Legacy or specialised transport layers linking controllers, protection devices, and supervisory systems.",
        },
        {
            "id": "safety_recovery",
            "parent_id": None,
            "label": "Safety, Protection, and Recovery",
            "category": "safety",
            "description": "Protection relays, trips, shutdown paths, emergency power, black-start dependencies, and recovery sequencing.",
            "attack_surfaces": ["Protection settings", "Trip logic", "Manual overrides"],
        },
        {
            "id": "shutdown_trip_logic",
            "parent_id": "safety_recovery",
            "label": "Trips, Shutdowns, and Interlocks",
            "category": "safety",
            "description": "Automated or manual protective functions preventing unsafe plant operation.",
        },
        {
            "id": "blackstart_backup",
            "parent_id": "safety_recovery",
            "label": "Backup Power and Black-Start Dependencies",
            "category": "safety",
            "description": "Recovery dependencies required to restore generation after a disruptive event.",
        },
        {
            "id": "monitoring_process_power",
            "parent_id": None,
            "label": "Monitoring, Detection, and Plant Process",
            "category": "monitoring",
            "description": "Alarm management, SOE/event logs, operator runbooks, and maintenance windows that affect visibility and restoration.",
            "telemetry": ["SOE logs", "Alarm manager", "Historian trends", "Operator narratives"],
        },
        {
            "id": "alarm_event_sequences",
            "parent_id": "monitoring_process_power",
            "label": "Alarm and Event Sequence Management",
            "category": "monitoring",
            "description": "Operational telemetry used to distinguish faults, operator error, and malicious manipulation.",
        },
        {
            "id": "maintenance_change_windows",
            "parent_id": "monitoring_process_power",
            "label": "Maintenance and Change Windows",
            "category": "process",
            "description": "Planned work periods that can create concealment, degraded monitoring, or unusual trust exceptions.",
        },
    ],
}


NUCLEAR_POWER_PLANT_CATALOG = {
    "id": "nuclear_power_plant",
    "name": "Nuclear Power Plant",
    "sector": "Nuclear Generation / High Safety Environment",
    "description": (
        "Reference decomposition of a nuclear generating station, including protected areas, reactor and turbine support systems, "
        "plant control, safety systems, and compliance-driven operating processes."
    ),
    "context_presets": ["nuclear_power_plant"],
    "nodes": [
        {
            "id": "nuclear_people_roles",
            "parent_id": None,
            "label": "People, Licensed Operations, and Trusted Parties",
            "category": "people",
            "description": "Licensed operators, reactor engineers, health physics, outage teams, and specialised OEM contractors working under strict procedural control.",
            "attack_surfaces": ["Procedure compliance", "Trusted contractors", "Emergency staffing", "Training systems"],
        },
        {
            "id": "licensed_ops_hp",
            "parent_id": "nuclear_people_roles",
            "label": "Licensed Operators, Reactor Engineers, and Health Physics",
            "category": "people",
            "description": "Core staff with authority over plant state, radiological controls, and abnormal event response.",
        },
        {
            "id": "refuelling_contractors_vendors",
            "parent_id": "nuclear_people_roles",
            "label": "Refuelling, Outage, and OEM Contractors",
            "category": "people",
            "description": "Periodic support staff with elevated physical and logical reach during refuelling or major maintenance.",
        },
        {
            "id": "protected_area_physical",
            "parent_id": None,
            "label": "Physical Security, Protected Area, and Vital Areas",
            "category": "physical",
            "description": "Layered security boundaries, access control, vital cabinets, protected-area workflows, and physical protection systems.",
            "telemetry": ["Access portals", "Protected-area alarms", "Guard logs", "Vital-area entry history"],
        },
        {
            "id": "perimeter_protected_vital",
            "parent_id": "protected_area_physical",
            "label": "Perimeter, Protected Area, and Vital Areas",
            "category": "physical",
            "description": "Escalating access-control zones with different threat assumptions and response obligations.",
        },
        {
            "id": "reactor_turbine_plant",
            "parent_id": "protected_area_physical",
            "label": "Reactor, Turbine, and Balance-of-Plant Access",
            "category": "physical",
            "description": "Physical reach into plant systems, cabinets, field devices, and maintenance spaces around critical equipment.",
        },
        {
            "id": "nuclear_it_support",
            "parent_id": None,
            "label": "IT Enterprise and Support Systems",
            "category": "it",
            "description": "Corporate IT, engineering documentation, training, maintenance, and identity services that intersect with plant operations.",
            "attack_surfaces": ["AD", "Email", "Doc control", "Training and simulation environments"],
        },
        {
            "id": "doc_control_training",
            "parent_id": "nuclear_it_support",
            "label": "Documentation, Training, and Knowledge Systems",
            "category": "service",
            "description": "Systems storing procedures, drawings, maintenance instructions, and operator training materials.",
        },
        {
            "id": "identity_collaboration_nuclear",
            "parent_id": "nuclear_it_support",
            "label": "Identity, Collaboration, and Administrative Workflow",
            "category": "it",
            "description": "Enterprise identity and communications systems that can influence plant-adjacent trust and coordination.",
        },
        {
            "id": "nuclear_ot_control",
            "parent_id": None,
            "label": "Plant Control and OT Systems",
            "category": "ot",
            "description": "DCS, PLCs, HMIs, historians, and specialised control environments supporting reactor, turbine, and auxiliary processes.",
            "attack_surfaces": ["Engineering workstations", "Logic downloads", "Historian bridges", "Removable media"],
        },
        {
            "id": "plant_dcs_historians",
            "parent_id": "nuclear_ot_control",
            "label": "Plant DCS, HMIs, and Historians",
            "category": "ot",
            "description": "Supervisory control and operational history for the plant and auxiliary systems.",
        },
        {
            "id": "auxiliary_plcs_controllers",
            "parent_id": "nuclear_ot_control",
            "label": "Auxiliary PLCs and Specialised Controllers",
            "category": "ot",
            "description": "Control endpoints managing cooling water, feed systems, balance-of-plant, and non-safety support processes.",
        },
        {
            "id": "nuclear_safety",
            "parent_id": None,
            "label": "Safety, Protection, and Emergency Functions",
            "category": "safety",
            "description": "Reactor protection, engineered safety features, emergency preparedness, and procedural safety barriers.",
            "attack_surfaces": ["Setpoint integrity", "Safety logic changes", "Emergency communication paths"],
        },
        {
            "id": "reactor_protection_esf",
            "parent_id": "nuclear_safety",
            "label": "Reactor Protection and Engineered Safety Features",
            "category": "safety",
            "description": "Protective trips, emergency core cooling, and supporting logic that should remain isolated and trustworthy.",
        },
        {
            "id": "emergency_preparedness",
            "parent_id": "nuclear_safety",
            "label": "Emergency Preparedness and Response Systems",
            "category": "safety",
            "description": "Notification, crisis management, and procedural recovery capabilities relied on during abnormal or high-consequence events.",
        },
        {
            "id": "nuclear_networking",
            "parent_id": None,
            "label": "Networking, Segregation, and External Support Paths",
            "category": "networking",
            "description": "Segmentation, one-way transfers, remote support, and tightly controlled data movement between plant and enterprise environments.",
            "telemetry": ["Firewall logs", "Transfer approvals", "Jump host sessions", "Data diode events"],
        },
        {
            "id": "segmentation_data_diodes",
            "parent_id": "nuclear_networking",
            "label": "Segmentation, Data Diodes, and Controlled Transfers",
            "category": "networking",
            "description": "Architectural controls intended to constrain bidirectional reach and limit attack propagation.",
        },
        {
            "id": "vendor_support_paths_nuclear",
            "parent_id": "nuclear_networking",
            "label": "Vendor and Specialist Support Paths",
            "category": "networking",
            "description": "Highly controlled remote or temporary access used for specialised maintenance or diagnostics.",
        },
        {
            "id": "fuel_radiological_support",
            "parent_id": None,
            "label": "Fuel Handling, Radiological Support, and Auxiliary Services",
            "category": "service",
            "description": "Fuel handling, spent fuel support, chemistry, radiation monitoring, and other critical auxiliary processes.",
            "attack_surfaces": ["Support instrumentation", "Procedure-driven operations", "Special-purpose workstations"],
        },
        {
            "id": "fuel_spent_fuel_systems",
            "parent_id": "fuel_radiological_support",
            "label": "Fuel and Spent Fuel Support Systems",
            "category": "service",
            "description": "Systems and workflows supporting fuel movement, pool monitoring, and associated handling operations.",
        },
        {
            "id": "radiation_monitoring_chemistry",
            "parent_id": "fuel_radiological_support",
            "label": "Radiation Monitoring and Chemistry Support",
            "category": "service",
            "description": "Instrumentation and support services that feed safety decisions and compliance posture.",
        },
        {
            "id": "monitoring_process_nuclear",
            "parent_id": None,
            "label": "Monitoring, Compliance, and Process Discipline",
            "category": "monitoring",
            "description": "Alarm handling, compliance evidence, procedure adherence, and emergency drills that strongly influence anomaly detection and recovery quality.",
            "telemetry": ["Alarm/event logs", "Procedure sign-offs", "Compliance records", "Drill history"],
        },
        {
            "id": "compliance_event_review",
            "parent_id": "monitoring_process_nuclear",
            "label": "Compliance and Event Review",
            "category": "monitoring",
            "description": "Regulatory and internal review processes that preserve evidence and constrain operational changes.",
        },
        {
            "id": "procedure_discipline",
            "parent_id": "monitoring_process_nuclear",
            "label": "Procedure Discipline and Shift Management",
            "category": "process",
            "description": "Formal controls that can either suppress malicious drift or create exploitable expectations and blind spots.",
        },
    ],
}


ENVIRONMENT_CATALOGS = [
    DATA_CENTRE_CATALOG,
    TELECOMS_BASE_STATION_CATALOG,
    TELECOMS_5G_CORE_CATALOG,
    ELECTRICAL_SUBSTATION_CATALOG,
    WATER_TREATMENT_PLANT_CATALOG,
    PORT_MARITIME_TERMINAL_CATALOG,
    OIL_GAS_PIPELINE_CATALOG,
    MANUFACTURING_FACILITY_CATALOG,
    PHARMA_MANUFACTURING_PLANT_CATALOG,
    EV_CHARGING_NETWORK_CATALOG,
    AIRPORT_CATALOG,
    MILITARY_HEADQUARTERS_CATALOG,
    OIL_REFINERY_CATALOG,
    DRILLING_RIG_CATALOG,
    DEFENCE_MANUFACTURING_PLANT_CATALOG,
    SHIPYARD_NAVAL_BASE_CATALOG,
    LNG_TERMINAL_CATALOG,
    SATELLITE_GROUND_STATION_CATALOG,
    POWER_STATION_CATALOG,
    NUCLEAR_POWER_PLANT_CATALOG,
]
