"""Additional environment catalogs for manufacturing, energy, and space environments."""

from __future__ import annotations


MANUFACTURING_FACILITY_CATALOG = {
    "id": "manufacturing_facility",
    "name": "Manufacturing Facility",
    "sector": "Industrial Manufacturing / Factory OT",
    "description": (
        "Reference decomposition of a modern manufacturing facility, including plant operations, production lines, "
        "industrial control systems, MES and quality systems, warehousing, and maintenance or safety dependencies."
    ),
    "context_presets": ["manufacturing_facility"],
    "nodes": [
        {
            "id": "mfg_people_roles",
            "parent_id": None,
            "label": "People, Operations, and Trusted Parties",
            "category": "people",
            "description": "Production supervisors, controls engineers, maintenance teams, OEM vendors, and contractors influencing uptime and process integrity.",
            "attack_surfaces": ["Shift handovers", "Maintenance approvals", "Vendor trust", "Temporary engineering access"],
        },
        {
            "id": "mfg_ops_engineers",
            "parent_id": "mfg_people_roles",
            "label": "Production, Maintenance, and Controls Engineers",
            "category": "people",
            "description": "Plant staff responsible for line state, recipe or setpoint changes, maintenance activities, and abnormal-event handling.",
        },
        {
            "id": "mfg_oems_integrators",
            "parent_id": "mfg_people_roles",
            "label": "OEMs, Integrators, and Service Contractors",
            "category": "people",
            "description": "Third parties maintaining robotics, PLCs, HMIs, machine vision, packaging lines, and industrial networks.",
            "management_interfaces": ["Vendor VPN", "Field laptops", "Remote support portals"],
        },
        {
            "id": "mfg_physical_process",
            "parent_id": None,
            "label": "Physical Plant, Production Lines, and Warehousing",
            "category": "physical",
            "description": "Factory floor areas, line-side panels, machine cells, utility spaces, warehouse systems, and shipping or receiving zones.",
            "telemetry": ["Badge logs", "CCTV", "Equipment alarms", "Work permits"],
        },
        {
            "id": "mfg_line_cells_panels",
            "parent_id": "mfg_physical_process",
            "label": "Production Cells, Panels, and Machine Access",
            "category": "physical",
            "description": "Operator stations, control panels, machine cells, local HMIs, and exposed service ports on the line.",
        },
        {
            "id": "mfg_warehouse_logistics",
            "parent_id": "mfg_physical_process",
            "label": "Warehouse, Material Handling, and Shipping",
            "category": "service",
            "description": "Conveyors, barcode systems, AGVs, warehouse workflows, and receiving or dispatch processes feeding production.",
        },
        {
            "id": "mfg_ot_control",
            "parent_id": None,
            "label": "Industrial Control, Robotics, and Supervisory Systems",
            "category": "ot",
            "description": "PLCs, HMIs, SCADA, robot controllers, engineering workstations, and line-control systems operating the factory process.",
            "attack_surfaces": ["Engineering workstations", "Robot teach pendants", "PLC logic downloads", "Machine-service accounts"],
        },
        {
            "id": "mfg_plc_hmi_robotics",
            "parent_id": "mfg_ot_control",
            "label": "PLCs, HMIs, Robotics, and Line Controllers",
            "category": "ot",
            "description": "Core automation platforms controlling assembly, packaging, motion, and line coordination.",
            "common_protocols": ["PROFINET", "EtherNet/IP", "OPC UA", "Modbus TCP"],
            "example_technologies": ["Siemens S7", "Rockwell ControlLogix", "ABB Robotics", "KUKA"],
        },
        {
            "id": "mfg_historians_vision",
            "parent_id": "mfg_ot_control",
            "label": "Historians, Vision Systems, and Industrial Data Services",
            "category": "ot",
            "description": "Operational history, machine vision, and analytics systems that affect throughput, quality, and anomaly detection.",
        },
        {
            "id": "mfg_it_business",
            "parent_id": None,
            "label": "MES, ERP, Quality, and Business Support Systems",
            "category": "it",
            "description": "Manufacturing execution, quality records, ERP, CMMS, and enterprise systems linked to planning and production trust.",
            "attack_surfaces": ["MES credentials", "Recipe change workflows", "Patching systems", "Supplier integrations"],
        },
        {
            "id": "mfg_mes_quality",
            "parent_id": "mfg_it_business",
            "label": "MES, Quality Systems, and Electronic Records",
            "category": "it",
            "description": "Production scheduling, genealogy, quality holds, and electronic records affecting output trust and traceability.",
        },
        {
            "id": "mfg_erp_cmms",
            "parent_id": "mfg_it_business",
            "label": "ERP, CMMS, and Production Planning",
            "category": "service",
            "description": "Maintenance, spares, work-order, and planning systems that shape what changes are considered legitimate.",
        },
        {
            "id": "mfg_network_remote",
            "parent_id": None,
            "label": "Industrial Networking, Remote Access, and Segmentation",
            "category": "networking",
            "description": "Cell and zone segmentation, industrial switches, wireless, plant DMZ services, and vendor support paths.",
            "telemetry": ["Switch logs", "Firewall events", "Remote sessions", "Wireless alerts"],
        },
        {
            "id": "mfg_cells_zones_dmz",
            "parent_id": "mfg_network_remote",
            "label": "Cells, Zones, Plant DMZ, and Shared Services",
            "category": "networking",
            "description": "Architectural boundaries between enterprise IT, MES, line control, and safety-critical machine environments.",
        },
        {
            "id": "mfg_vendor_wireless",
            "parent_id": "mfg_network_remote",
            "label": "Vendor Remote Access, Wireless, and Mobile Tooling",
            "category": "networking",
            "description": "Trusted pathways and mobile or wireless systems used by maintenance teams and line support personnel.",
        },
        {
            "id": "mfg_safety_monitoring",
            "parent_id": None,
            "label": "Safety, Quality, and Recovery Process",
            "category": "monitoring",
            "description": "Safety PLCs, interlocks, alarm review, change control, and quality-response workflows affecting detection and restoration.",
            "telemetry": ["Alarm journals", "Safety events", "Quality deviations", "Shift logs"],
        },
        {
            "id": "mfg_safety_interlocks",
            "parent_id": "mfg_safety_monitoring",
            "label": "Safety PLCs, Interlocks, and Protective Functions",
            "category": "safety",
            "description": "Protective logic intended to prevent unsafe machine states, collisions, or hazardous operation.",
        },
        {
            "id": "mfg_change_quality_response",
            "parent_id": "mfg_safety_monitoring",
            "label": "Change Control, Quality Deviations, and Incident Response",
            "category": "process",
            "description": "Operational processes that can either expose manipulation quickly or provide concealment during degraded production periods.",
        },
    ],
}


EV_CHARGING_NETWORK_CATALOG = {
    "id": "ev_charging_network",
    "name": "EV Charging Network",
    "sector": "Distributed Energy / EV Charging / Connected Infrastructure",
    "description": (
        "Reference decomposition of an EV charging network, including charger hardware, site operations, cloud management, "
        "payment and identity systems, grid-facing dependencies, and field maintenance workflows."
    ),
    "context_presets": ["ev_charging_network"],
    "nodes": [
        {
            "id": "ev_people_roles",
            "parent_id": None,
            "label": "People, CPO Operations, and Trusted Parties",
            "category": "people",
            "description": "Charge-point operator teams, site hosts, electricians, payment providers, and charger vendors influencing trust and recovery.",
            "attack_surfaces": ["Installer access", "Remote support", "Billing operations", "Third-party maintenance"],
        },
        {
            "id": "ev_cpo_ops_support",
            "parent_id": "ev_people_roles",
            "label": "CPO Operations, NOC, and Customer Support",
            "category": "people",
            "description": "Staff managing charger availability, remote actions, tariffs, customer sessions, and operational incidents.",
        },
        {
            "id": "ev_field_techs_vendors",
            "parent_id": "ev_people_roles",
            "label": "Electricians, Field Technicians, and OEM Vendors",
            "category": "people",
            "description": "Trusted parties with physical and logical access to charger cabinets, firmware, and local networking.",
            "management_interfaces": ["Field apps", "Vendor portals", "Maintenance laptops"],
        },
        {
            "id": "ev_physical_sites",
            "parent_id": None,
            "label": "Charging Sites, Cabinets, and Physical Access",
            "category": "physical",
            "description": "Public or fleet charging locations, cabinets, pedestals, local networking, breakers, and adjacent site infrastructure.",
            "telemetry": ["Cabinet tamper alarms", "CCTV", "Breaker events", "Site access logs"],
        },
        {
            "id": "ev_chargers_cabinets",
            "parent_id": "ev_physical_sites",
            "label": "Chargers, Cabinets, Connectors, and Service Ports",
            "category": "physical",
            "description": "Charge points, local controllers, exposed maintenance ports, and hardware trust anchors on each site.",
        },
        {
            "id": "ev_site_power_switchgear",
            "parent_id": "ev_physical_sites",
            "label": "Site Switchgear, Meters, and Power Distribution",
            "category": "service",
            "description": "Electrical distribution, metering, load management hardware, and utility-facing site infrastructure.",
        },
        {
            "id": "ev_ot_control",
            "parent_id": None,
            "label": "Charger Control, Firmware, and Site Management",
            "category": "ot",
            "description": "Embedded charger controllers, local load-balancing systems, firmware update mechanisms, and site gateways.",
            "attack_surfaces": ["Firmware updates", "Local admin interfaces", "Debug ports", "Remote control commands"],
        },
        {
            "id": "ev_charger_firmware_local",
            "parent_id": "ev_ot_control",
            "label": "Charger Firmware, Local Admin, and Embedded Services",
            "category": "ot",
            "description": "On-device services, local configuration paths, firmware validation, and embedded control logic on chargers.",
        },
        {
            "id": "ev_site_gateways_load",
            "parent_id": "ev_ot_control",
            "label": "Site Gateways, Load Balancing, and Energy Management",
            "category": "ot",
            "description": "Edge gateways coordinating groups of chargers, smart load sharing, and local energy constraints.",
            "common_protocols": ["OCPP", "Modbus", "MQTT", "HTTPS"],
        },
        {
            "id": "ev_cloud_business",
            "parent_id": None,
            "label": "Cloud Platform, Billing, and Identity Systems",
            "category": "it",
            "description": "Central management platforms, mobile apps, payment processing, roaming platforms, and operator admin portals.",
            "attack_surfaces": ["Operator APIs", "Payment flows", "Mobile app auth", "Roaming integrations"],
        },
        {
            "id": "ev_csms_mobile_billing",
            "parent_id": "ev_cloud_business",
            "label": "CSMS, Mobile Applications, and Billing",
            "category": "it",
            "description": "Central system management, customer identity, payment handling, and session orchestration across the network.",
        },
        {
            "id": "ev_roaming_partner_api",
            "parent_id": "ev_cloud_business",
            "label": "Roaming, Partner APIs, and Fleet Integrations",
            "category": "service",
            "description": "Third-party connections for fleet management, roaming, utility coordination, or energy-market participation.",
        },
        {
            "id": "ev_network_grid",
            "parent_id": None,
            "label": "Communications, Utility Interfaces, and Grid Dependencies",
            "category": "networking",
            "description": "Cellular backhaul, site networking, utility telemetry, and coordination surfaces that tie charging behaviour to the grid.",
            "telemetry": ["Cellular link health", "VPN logs", "AMI or utility telemetry", "API audit logs"],
        },
        {
            "id": "ev_cellular_vpn_site",
            "parent_id": "ev_network_grid",
            "label": "Cellular, VPN, and Site Networking",
            "category": "networking",
            "description": "Backhaul and remote-management pathways between chargers, gateways, and central services.",
        },
        {
            "id": "ev_grid_demand_response",
            "parent_id": "ev_network_grid",
            "label": "Grid Services, Demand Response, and Utility Coordination",
            "category": "networking",
            "description": "Signals and trust paths allowing charging demand to interact with utility, tariff, or balancing systems.",
        },
        {
            "id": "ev_monitoring_recovery",
            "parent_id": None,
            "label": "Monitoring, Fraud Detection, and Recovery Process",
            "category": "monitoring",
            "description": "Network health, charger alarms, payment fraud monitoring, maintenance workflows, and emergency response shaping resilience.",
            "telemetry": ["Charger alarms", "Payment fraud alerts", "Remote action logs", "Firmware rollout history"],
        },
        {
            "id": "ev_alarm_fraud_monitoring",
            "parent_id": "ev_monitoring_recovery",
            "label": "Operational Alarms, Fraud Monitoring, and Telemetry",
            "category": "monitoring",
            "description": "Signals used to detect charger abuse, coordinated outages, payment misuse, or suspicious load manipulation.",
        },
        {
            "id": "ev_maintenance_firmware_response",
            "parent_id": "ev_monitoring_recovery",
            "label": "Maintenance, Firmware Rollout, and Incident Response",
            "category": "process",
            "description": "Procedures that can either contain charger compromise quickly or amplify it through broad rollouts and trust exceptions.",
        },
    ],
}


SATELLITE_GROUND_STATION_CATALOG = {
    "id": "satellite_ground_station",
    "name": "Satellite Ground Station",
    "sector": "Satellite Communications / Ground Segment",
    "description": (
        "Reference decomposition of a satellite ground station, including mission operations, TT&C systems, antenna and RF assets, "
        "teleports and backhaul, support vendors, and contingency procedures."
    ),
    "context_presets": ["satellite_ground_station"],
    "nodes": [
        {
            "id": "sat_people_roles",
            "parent_id": None,
            "label": "People, Mission Operations, and Trusted Parties",
            "category": "people",
            "description": "Mission operators, RF engineers, TT&C specialists, schedulers, and vendors responsible for uplink, downlink, and recovery.",
            "attack_surfaces": ["Mission approvals", "Vendor trust", "Temporary support access", "Scheduling changes"],
        },
        {
            "id": "sat_mission_ops_engineers",
            "parent_id": "sat_people_roles",
            "label": "Mission Control, RF, and Ground Segment Engineers",
            "category": "people",
            "description": "Core staff managing contact windows, command preparation, tracking, and ground-segment health.",
        },
        {
            "id": "sat_vendors_contractors",
            "parent_id": "sat_people_roles",
            "label": "Equipment Vendors, Integrators, and Contractors",
            "category": "people",
            "description": "Third parties maintaining modems, antenna controllers, tracking systems, timing, or facility infrastructure.",
            "management_interfaces": ["Vendor VPN", "Support portals", "Field laptops"],
        },
        {
            "id": "sat_physical_rf",
            "parent_id": None,
            "label": "Physical Facility, Antennas, and RF Plant",
            "category": "physical",
            "description": "Antenna pads, radomes, feed systems, RF chains, control rooms, and physical access to mission-critical equipment.",
            "telemetry": ["Perimeter alarms", "Camera feeds", "Antenna health alarms", "Access events"],
        },
        {
            "id": "sat_antennas_rf_chain",
            "parent_id": "sat_physical_rf",
            "label": "Antennas, Feed Systems, and RF Chain",
            "category": "physical",
            "description": "Antenna structures, amplifiers, low-noise chains, combiners, and switching matrices that support uplink and downlink.",
        },
        {
            "id": "sat_control_rooms_power",
            "parent_id": "sat_physical_rf",
            "label": "Control Rooms, Power, and Environmental Support",
            "category": "service",
            "description": "Operator spaces, UPS, cooling, generators, timing, and other site infrastructure required to keep contacts active.",
        },
        {
            "id": "sat_control_command",
            "parent_id": None,
            "label": "Mission Control, TT&C, and Payload Support Systems",
            "category": "ot",
            "description": "Command generation, telemetry processing, tracking, ranging, and mission support systems linked to spacecraft operations.",
            "attack_surfaces": ["Command authorization", "Telemetry processors", "Tracking software", "Key material"],
        },
        {
            "id": "sat_ttc_mission_systems",
            "parent_id": "sat_control_command",
            "label": "TT&C, Scheduling, and Mission Control Software",
            "category": "ot",
            "description": "Ground software used to plan passes, generate command loads, and monitor spacecraft state.",
        },
        {
            "id": "sat_modems_decoders",
            "parent_id": "sat_control_command",
            "label": "Modems, Telemetry Decoders, and Processing Systems",
            "category": "ot",
            "description": "Systems converting RF signals into operational telemetry and payload data or transmitting validated commands.",
        },
        {
            "id": "sat_it_networking",
            "parent_id": None,
            "label": "Ground Segment IT, Networking, and Teleport Backhaul",
            "category": "networking",
            "description": "Mission networks, teleport backhaul, IP routing, remote operations, and segmentation between corporate and ground-segment systems.",
            "telemetry": ["Router logs", "VPN sessions", "Network monitoring", "Transfer records"],
        },
        {
            "id": "sat_mission_network_dmz",
            "parent_id": "sat_it_networking",
            "label": "Mission Networks, DMZs, and Remote Operations",
            "category": "networking",
            "description": "Boundaries controlling operator access, remote contact operations, and data exchange into the ground segment.",
        },
        {
            "id": "sat_teleport_external_links",
            "parent_id": "sat_it_networking",
            "label": "Teleport Backhaul, External Links, and Partner Interfaces",
            "category": "networking",
            "description": "Connectivity to mission data users, control centres, service providers, and external scheduling or payload partners.",
        },
        {
            "id": "sat_identity_monitoring",
            "parent_id": None,
            "label": "Identity, Key Management, and Monitoring Process",
            "category": "monitoring",
            "description": "Authentication, command approval, RF anomaly detection, contact review, and contingency procedures that protect mission integrity.",
            "telemetry": ["Auth logs", "Command audit trails", "RF anomaly alerts", "Contingency drill records"],
        },
        {
            "id": "sat_identity_keys",
            "parent_id": "sat_identity_monitoring",
            "label": "Identity, Key Material, and Command Authorization",
            "category": "safety",
            "description": "Processes and systems ensuring only trusted personnel and approved command products reach spacecraft interfaces.",
        },
        {
            "id": "sat_monitoring_contingency",
            "parent_id": "sat_identity_monitoring",
            "label": "Monitoring, Contact Review, and Contingency Response",
            "category": "process",
            "description": "Operational review and fallback procedures shaping how fast anomalous contacts, jamming, or uplink abuse are detected and contained.",
        },
    ],
}


PHARMA_MANUFACTURING_PLANT_CATALOG = {
    "id": "pharma_manufacturing_plant",
    "name": "Pharma Manufacturing Plant",
    "sector": "Pharmaceutical Manufacturing / Regulated OT",
    "description": (
        "Reference decomposition of a pharmaceutical manufacturing plant, including batch control, cleanroom and environmental controls, "
        "quality and laboratory systems, cold-chain dependencies, and compliance-heavy operational workflows."
    ),
    "context_presets": ["pharma_manufacturing_plant"],
    "nodes": [
        {
            "id": "pharma_people_roles",
            "parent_id": None,
            "label": "People, Quality, and Trusted Parties",
            "category": "people",
            "description": "Production supervisors, QA or QC teams, validation engineers, maintenance staff, and OEM vendors controlling process trust.",
            "attack_surfaces": ["Batch approvals", "Deviation handling", "Vendor trust", "Validation workflows"],
        },
        {
            "id": "pharma_ops_qa_qc",
            "parent_id": "pharma_people_roles",
            "label": "Production, QA, QC, and Validation Teams",
            "category": "people",
            "description": "Staff responsible for batch execution, review by exception, deviation management, and release decisions.",
        },
        {
            "id": "pharma_oems_integrators",
            "parent_id": "pharma_people_roles",
            "label": "OEMs, Integrators, and Specialist Contractors",
            "category": "people",
            "description": "Third parties maintaining DCS platforms, skids, environmental systems, analytical instruments, and packaging lines.",
        },
        {
            "id": "pharma_physical_process",
            "parent_id": None,
            "label": "Physical Production Areas, Cleanrooms, and Storage",
            "category": "physical",
            "description": "Manufacturing suites, cleanrooms, utility rooms, warehousing, cold storage, and packaging or serialization areas.",
            "telemetry": ["Access logs", "Environmental alarms", "Cold-room alerts", "CCTV"],
        },
        {
            "id": "pharma_suites_cleanrooms",
            "parent_id": "pharma_physical_process",
            "label": "Production Suites, Cleanrooms, and Utilities",
            "category": "physical",
            "description": "Controlled manufacturing spaces and supporting utilities where contamination and process integrity are critical.",
        },
        {
            "id": "pharma_storage_packaging",
            "parent_id": "pharma_physical_process",
            "label": "Cold Storage, Warehousing, and Packaging",
            "category": "service",
            "description": "Storage and packaging systems whose integrity affects chain of custody, temperature-sensitive product, and release confidence.",
        },
        {
            "id": "pharma_ot_control",
            "parent_id": None,
            "label": "Batch Control, DCS, and Process Automation",
            "category": "ot",
            "description": "ISA-88 batch systems, DCS, PLCs, HMIs, historians, and process skids governing recipe execution and line state.",
            "attack_surfaces": ["Recipe changes", "Engineering workstations", "PLC logic", "Operator HMIs"],
        },
        {
            "id": "pharma_batch_dcs",
            "parent_id": "pharma_ot_control",
            "label": "Batch Control, DCS, and Engineering Workstations",
            "category": "ot",
            "description": "Core supervisory and engineering systems used to manage formulas, process parameters, and production sequencing.",
        },
        {
            "id": "pharma_plc_skids_ems",
            "parent_id": "pharma_ot_control",
            "label": "PLCs, Packaging Skids, and Environmental Monitoring",
            "category": "ot",
            "description": "Line-level controllers and environmental monitoring systems affecting both process state and contamination risk.",
            "common_protocols": ["OPC UA", "Modbus", "PROFINET", "EtherNet/IP"],
        },
        {
            "id": "pharma_quality_it",
            "parent_id": None,
            "label": "LIMS, Quality Systems, and Electronic Records",
            "category": "it",
            "description": "Laboratory systems, eBR, deviation management, release workflows, and regulated records supporting product trust.",
            "attack_surfaces": ["LIMS credentials", "Electronic signatures", "Record edits", "Report generation"],
        },
        {
            "id": "pharma_lims_qms_ebr",
            "parent_id": "pharma_quality_it",
            "label": "LIMS, QMS, eBR, and Deviation Systems",
            "category": "it",
            "description": "Critical quality and evidence systems that can hide adulteration, process drift, or failed batches if compromised.",
        },
        {
            "id": "pharma_analytical_instruments",
            "parent_id": "pharma_quality_it",
            "label": "Analytical Instruments and Lab Workstations",
            "category": "service",
            "description": "HPLC, spectroscopy, and other instrument platforms used to validate drug quality and release decisions.",
        },
        {
            "id": "pharma_network_remote",
            "parent_id": None,
            "label": "Plant Networking, Vendor Access, and Segmentation",
            "category": "networking",
            "description": "Plant DMZs, quality-system interfaces, remote support paths, and network segregation between enterprise, lab, and OT systems.",
            "telemetry": ["Firewall logs", "Remote access records", "Network taps", "Access approvals"],
        },
        {
            "id": "pharma_dmz_lab_ot",
            "parent_id": "pharma_network_remote",
            "label": "Plant DMZ, Lab Networks, and OT Boundaries",
            "category": "networking",
            "description": "Boundaries that should constrain movement between quality systems, production OT, and broader enterprise services.",
        },
        {
            "id": "pharma_vendor_remote",
            "parent_id": "pharma_network_remote",
            "label": "Vendor Support, Temporary Access, and Transfer Paths",
            "category": "networking",
            "description": "Temporary access and file-transfer workflows used during validation, maintenance, and incident response.",
        },
        {
            "id": "pharma_monitoring_compliance",
            "parent_id": None,
            "label": "Monitoring, Compliance, and Recovery Process",
            "category": "monitoring",
            "description": "Alarm review, audit trails, release holds, and CAPA or deviation workflows that shape detection and recovery confidence.",
            "telemetry": ["Audit trails", "Batch alarms", "Deviation logs", "CAPA records"],
        },
        {
            "id": "pharma_audit_release",
            "parent_id": "pharma_monitoring_compliance",
            "label": "Audit Trails, Release Controls, and Data Integrity",
            "category": "monitoring",
            "description": "Evidence and release processes used to detect unauthorised changes and preserve product trust.",
        },
        {
            "id": "pharma_deviation_capa_response",
            "parent_id": "pharma_monitoring_compliance",
            "label": "Deviation Handling, CAPA, and Incident Response",
            "category": "process",
            "description": "Procedural controls that determine whether sabotage is contained quickly or hidden inside expected manufacturing variability.",
        },
    ],
}


LNG_TERMINAL_CATALOG = {
    "id": "lng_terminal",
    "name": "LNG Terminal",
    "sector": "Oil & Gas / LNG / Terminal OT",
    "description": (
        "Reference decomposition of an LNG terminal, including process operations, cryogenic storage and transfer, DCS and SIS layers, "
        "marine and utility interfaces, vendor access, and high-consequence shutdown or emergency workflows."
    ),
    "context_presets": ["lng_terminal"],
    "nodes": [
        {
            "id": "lng_people_roles",
            "parent_id": None,
            "label": "People, Operations, and Trusted Parties",
            "category": "people",
            "description": "Console operators, process engineers, marine coordinators, contractors, and OEM vendors shaping access and shutdown decisions.",
            "attack_surfaces": ["Permit-to-work", "Marine scheduling", "Vendor trust", "Emergency change windows"],
        },
        {
            "id": "lng_console_ops_engineers",
            "parent_id": "lng_people_roles",
            "label": "Console Operators, Process Engineers, and Marine Coordination",
            "category": "people",
            "description": "Operational staff managing storage, boil-off gas, unloading, regasification, and abnormal-event handling.",
        },
        {
            "id": "lng_oems_contractors",
            "parent_id": "lng_people_roles",
            "label": "OEMs, Contractors, and Specialist Support",
            "category": "people",
            "description": "Trusted vendors maintaining cryogenic instrumentation, DCS, SIS, compressors, loading arms, and fire or gas systems.",
            "management_interfaces": ["Vendor VPN", "Temporary engineering access", "Field laptops"],
        },
        {
            "id": "lng_physical_process",
            "parent_id": None,
            "label": "Cryogenic Process Areas, Storage, and Marine Interfaces",
            "category": "physical",
            "description": "Tank farms, vaporizers, compressors, loading arms, jetty interfaces, and utility systems supporting LNG movement and storage.",
            "telemetry": ["Gas detection", "Tank alarms", "Jetty access logs", "Perimeter alarms"],
        },
        {
            "id": "lng_tanks_transfer_process",
            "parent_id": "lng_physical_process",
            "label": "Storage Tanks, Transfer Systems, and Process Equipment",
            "category": "physical",
            "description": "Cryogenic process assets whose manipulation can create spills, overpressure, boil-off, or extended outage conditions.",
        },
        {
            "id": "lng_jetty_utilities_fire",
            "parent_id": "lng_physical_process",
            "label": "Jetty, Utilities, Power, and Fire or Gas Systems",
            "category": "service",
            "description": "Marine loading areas, utilities, flare support, emergency power, and detection or suppression systems around the process.",
        },
        {
            "id": "lng_ot_control",
            "parent_id": None,
            "label": "DCS, SIS, and Process Control",
            "category": "ot",
            "description": "DCS, PLCs, HMIs, SIS, historians, and compressor or loading controls managing terminal state and safety barriers.",
            "attack_surfaces": ["Engineering workstations", "Safety logic changes", "Historian bridges", "Controller downloads"],
        },
        {
            "id": "lng_dcs_hmi_eng",
            "parent_id": "lng_ot_control",
            "label": "DCS, HMIs, and Engineering Workstations",
            "category": "ot",
            "description": "Supervisory and engineering layers used to view process state, alter control strategies, and manage terminal operations.",
        },
        {
            "id": "lng_sis_plc_process",
            "parent_id": "lng_ot_control",
            "label": "SIS, PLCs, and Cryogenic Process Skids",
            "category": "safety",
            "description": "Control and protective layers enforcing trips, shutdowns, and safeguards across compressors, valves, tanks, and transfer systems.",
            "common_protocols": ["Modbus", "OPC UA", "PROFINET", "EtherNet/IP"],
        },
        {
            "id": "lng_it_business",
            "parent_id": None,
            "label": "Plant IT, Scheduling, and Documentation Systems",
            "category": "it",
            "description": "Identity, maintenance, marine scheduling, document control, and business-support systems that intersect with terminal operations.",
            "attack_surfaces": ["Identity systems", "Maintenance records", "Document control", "Vendor portals"],
        },
        {
            "id": "lng_identity_maintenance",
            "parent_id": "lng_it_business",
            "label": "Identity, Maintenance, and Work Management",
            "category": "it",
            "description": "Enterprise and plant IT services shaping who can access terminal systems and when work is considered legitimate.",
        },
        {
            "id": "lng_marine_docs_planning",
            "parent_id": "lng_it_business",
            "label": "Marine Planning, Documentation, and Logistics",
            "category": "service",
            "description": "Systems coordinating berth schedules, cargo planning, procedures, and process documentation.",
        },
        {
            "id": "lng_network_remote",
            "parent_id": None,
            "label": "Networking, Remote Access, and Industrial Communications",
            "category": "networking",
            "description": "Plant segmentation, radio and fibre links, vendor access, and communications between terminal, jetty, and utility environments.",
            "telemetry": ["Firewall events", "Switch logs", "Remote sessions", "Industrial comms alarms"],
        },
        {
            "id": "lng_dmz_jetty_links",
            "parent_id": "lng_network_remote",
            "label": "Plant DMZ, Jetty Links, and Utility Interfaces",
            "category": "networking",
            "description": "Boundaries and data paths connecting core process control to marine, power, and support environments.",
        },
        {
            "id": "lng_vendor_support_paths",
            "parent_id": "lng_network_remote",
            "label": "Vendor Remote Support and Temporary Access Paths",
            "category": "networking",
            "description": "Trusted access mechanisms used for maintenance, diagnostics, and emergency troubleshooting across the terminal.",
        },
        {
            "id": "lng_monitoring_emergency",
            "parent_id": None,
            "label": "Monitoring, Safety, and Emergency Response",
            "category": "monitoring",
            "description": "Alarm review, gas detection, event sequencing, emergency shutdown, and evacuation or recovery procedures affecting consequence management.",
            "telemetry": ["Alarm journals", "Gas detector history", "SOE logs", "Emergency drill records"],
        },
        {
            "id": "lng_alarm_safety_review",
            "parent_id": "lng_monitoring_emergency",
            "label": "Alarm Management, Safety Review, and Event Analysis",
            "category": "monitoring",
            "description": "Operational evidence used to distinguish equipment failure, process upset, and malicious manipulation of terminal state.",
        },
        {
            "id": "lng_shutdown_recovery_process",
            "parent_id": "lng_monitoring_emergency",
            "label": "Emergency Shutdown, Recovery, and Incident Command",
            "category": "process",
            "description": "High-consequence procedures that determine whether the terminal fails safe, recovers quickly, or cascades into wider outage or safety impact.",
        },
    ],
}


AIRPORT_CATALOG = {
    "id": "airport",
    "name": "Airport",
    "sector": "Aviation / Airport Operations / Transport Infrastructure",
    "description": (
        "Reference decomposition of an airport environment, including terminal and airside operations, passenger and airline systems, "
        "baggage and building automation, fuel and utility dependencies, and irregular-operations recovery workflows."
    ),
    "context_presets": ["airport"],
    "nodes": [
        {
            "id": "airport_people_roles",
            "parent_id": None,
            "label": "People, Airport Operations, and Trusted Parties",
            "category": "people",
            "description": "Airport operations staff, airlines, ground handlers, security teams, contractors, and authorities influencing trust and recovery.",
            "attack_surfaces": ["Badge approvals", "Shift handovers", "Third-party maintenance", "Operational exceptions"],
        },
        {
            "id": "airport_ops_airlines",
            "parent_id": "airport_people_roles",
            "label": "Airport Operations, Airlines, and Ground Handling",
            "category": "people",
            "description": "Operational teams coordinating gate allocation, ramp activity, passenger processing, baggage flow, and disruption handling.",
        },
        {
            "id": "airport_contractors_authorities",
            "parent_id": "airport_people_roles",
            "label": "Contractors, Security, and Regulatory Authorities",
            "category": "people",
            "description": "Trusted external parties with access to terminal systems, physical infrastructure, and safety-critical airport workflows.",
        },
        {
            "id": "airport_physical_terminal",
            "parent_id": None,
            "label": "Terminal, Airside, and Physical Access",
            "category": "physical",
            "description": "Passenger terminals, security checkpoints, airside areas, service corridors, baggage halls, and secure or restricted zones.",
            "telemetry": ["Badge logs", "CCTV", "Door alarms", "Vehicle access events"],
        },
        {
            "id": "airport_terminal_airside_zones",
            "parent_id": "airport_physical_terminal",
            "label": "Terminal, Airside, and Restricted Zones",
            "category": "physical",
            "description": "Physical boundaries controlling passenger, staff, and contractor movement between public, sterile, and airside areas.",
        },
        {
            "id": "airport_baggage_ramp_assets",
            "parent_id": "airport_physical_terminal",
            "label": "Baggage Halls, Ramp Equipment, and Service Areas",
            "category": "physical",
            "description": "Operational spaces and equipment where baggage systems, ramp vehicles, and airport service workflows converge.",
        },
        {
            "id": "airport_it_business",
            "parent_id": None,
            "label": "Airport IT, Passenger, and Airline Systems",
            "category": "it",
            "description": "AODB, FIDS, gate systems, passenger services, badging, and airport business platforms that coordinate movement and trust.",
            "attack_surfaces": ["AODB credentials", "Passenger-service apps", "Badging workflows", "Airline integrations"],
        },
        {
            "id": "airport_aodb_passenger_systems",
            "parent_id": "airport_it_business",
            "label": "AODB, FIDS, Gate, and Passenger Systems",
            "category": "it",
            "description": "Operational and passenger-facing systems that coordinate flights, gates, displays, and check-in or boarding workflows.",
        },
        {
            "id": "airport_badging_identity",
            "parent_id": "airport_it_business",
            "label": "Badging, Identity, and Access Administration",
            "category": "service",
            "description": "Processes and systems issuing airport credentials, access rights, and staff identity controls across tenants and contractors.",
        },
        {
            "id": "airport_ot_infrastructure",
            "parent_id": None,
            "label": "Baggage, Building, Fuel, and Airfield Systems",
            "category": "ot",
            "description": "Operational technology supporting baggage handling, BMS, access control, airfield services, utilities, and fuel support.",
            "attack_surfaces": ["PLC maintenance", "BMS head-end", "Service laptops", "Field controllers"],
        },
        {
            "id": "airport_baggage_bms_access",
            "parent_id": "airport_ot_infrastructure",
            "label": "Baggage Handling, BMS, and Access-Control Systems",
            "category": "ot",
            "description": "Automation and facility systems that directly affect passenger flow, secure access, and building operations.",
            "common_protocols": ["BACnet/IP", "Modbus", "OPC UA", "PROFINET"],
        },
        {
            "id": "airport_fuel_airfield_utilities",
            "parent_id": "airport_ot_infrastructure",
            "label": "Fuel Farm, Airfield Lighting, and Utility Support",
            "category": "service",
            "description": "Airport operational support systems affecting fueling, electrical support, stand availability, and airfield service resilience.",
        },
        {
            "id": "airport_network_partners",
            "parent_id": None,
            "label": "Networking, Partner Interfaces, and Communications",
            "category": "networking",
            "description": "Airport LANs, tenant networks, wireless, partner links, and remote support paths between airport stakeholders.",
            "telemetry": ["Firewall logs", "Wireless alerts", "Partner API logs", "Remote access sessions"],
        },
        {
            "id": "airport_partner_remote_links",
            "parent_id": "airport_network_partners",
            "label": "Airline, Tenant, and Third-Party Interfaces",
            "category": "networking",
            "description": "Data and trust paths between airport systems and airlines, handlers, customs, tenants, and support providers.",
        },
        {
            "id": "airport_wireless_mobile_radio",
            "parent_id": "airport_network_partners",
            "label": "Wireless, Mobile, and Operational Communications",
            "category": "networking",
            "description": "Wireless and mobile systems supporting staff devices, handheld scanners, operational radios, and field coordination.",
        },
        {
            "id": "airport_monitoring_recovery",
            "parent_id": None,
            "label": "Monitoring, Safety, and Irregular Operations Recovery",
            "category": "monitoring",
            "description": "SOC visibility, airport operations monitoring, safety escalation, and fallback procedures during disruption or security events.",
            "telemetry": ["SOC alerts", "Ops dashboards", "Facility alarms", "Incident logs"],
        },
        {
            "id": "airport_ops_monitoring",
            "parent_id": "airport_monitoring_recovery",
            "label": "Operational Monitoring, Alarms, and Visibility",
            "category": "monitoring",
            "description": "Signals used to detect service disruption, suspicious movement, partner failures, and baggage or access anomalies.",
        },
        {
            "id": "airport_irrops_emergency",
            "parent_id": "airport_monitoring_recovery",
            "label": "Irregular Operations, Emergency Response, and Manual Fallback",
            "category": "process",
            "description": "Operational procedures that determine whether disruption is contained with graceful degradation or cascades across the airport.",
        },
    ],
}


MILITARY_HEADQUARTERS_CATALOG = {
    "id": "military_headquarters",
    "name": "Military Headquarters",
    "sector": "Defence / Command / Enterprise Operations",
    "description": (
        "Reference decomposition of a military headquarters environment, including command staff and cleared personnel, secure spaces, "
        "enterprise IT, communications and mission-support systems, cross-domain boundaries, and continuity or incident-response processes."
    ),
    "context_presets": ["military_headquarters"],
    "nodes": [
        {
            "id": "milhq_people_roles",
            "parent_id": None,
            "label": "People, Command Staff, and Trusted Parties",
            "category": "people",
            "description": "Command staff, planners, cleared administrators, coalition partners, and contractors shaping access and decision authority.",
            "attack_surfaces": ["Cleared access", "Insider trust", "Contractor support", "Operational exceptions"],
        },
        {
            "id": "milhq_command_admin_staff",
            "parent_id": "milhq_people_roles",
            "label": "Command, Planning, and Administrative Staff",
            "category": "people",
            "description": "Personnel using command support systems, collaboration tools, and high-value communications in daily operations.",
        },
        {
            "id": "milhq_contractors_partners",
            "parent_id": "milhq_people_roles",
            "label": "Contractors, Coalition Partners, and Liaison Roles",
            "category": "people",
            "description": "Trusted external users and support teams with varying access to systems, facilities, and communications flows.",
        },
        {
            "id": "milhq_physical_secure",
            "parent_id": None,
            "label": "Physical Security, Secure Areas, and Access Control",
            "category": "physical",
            "description": "Perimeters, SCIFs, secure offices, briefing spaces, guard systems, and physical access paths into critical systems.",
            "telemetry": ["Access-control logs", "Guard records", "CCTV", "Visitor or escort logs"],
        },
        {
            "id": "milhq_perimeter_scifs",
            "parent_id": "milhq_physical_secure",
            "label": "Perimeter, SCIFs, and Restricted Workspaces",
            "category": "physical",
            "description": "Layered physical controls limiting movement into sensitive command, briefing, or intelligence environments.",
        },
        {
            "id": "milhq_comms_rooms_support",
            "parent_id": "milhq_physical_secure",
            "label": "Comms Rooms, IT Spaces, and Support Areas",
            "category": "physical",
            "description": "Rooms housing networking, communications, crypto, and support systems that underpin headquarters operations.",
        },
        {
            "id": "milhq_enterprise_it",
            "parent_id": None,
            "label": "Enterprise IT, Identity, and Knowledge Systems",
            "category": "it",
            "description": "Directory services, collaboration, document repositories, workflow systems, and enterprise services supporting headquarters activity.",
            "attack_surfaces": ["Identity admin", "Email and collaboration", "Document access", "Remote administration"],
        },
        {
            "id": "milhq_identity_collab",
            "parent_id": "milhq_enterprise_it",
            "label": "Identity, Collaboration, and Administrative Workflow",
            "category": "it",
            "description": "Enterprise identity and communications platforms that can provide broad reach into headquarters operations and trust relationships.",
        },
        {
            "id": "milhq_records_knowledge",
            "parent_id": "milhq_enterprise_it",
            "label": "Knowledge Repositories, Records, and Planning Systems",
            "category": "service",
            "description": "Systems holding plans, procedures, schedules, reports, and operational records with high intelligence value.",
        },
        {
            "id": "milhq_command_comms",
            "parent_id": None,
            "label": "Command, Communications, and Mission Support Systems",
            "category": "service",
            "description": "Secure messaging, briefing support, mission-planning, and communications systems used to coordinate command activity.",
            "attack_surfaces": ["Mission support apps", "Secure messaging", "Voice or video bridges", "Command workstations"],
        },
        {
            "id": "milhq_c2_workstations",
            "parent_id": "milhq_command_comms",
            "label": "Command Workstations, Briefing, and Mission Applications",
            "category": "service",
            "description": "Operational systems used to review status, share information, and coordinate activity across the headquarters.",
        },
        {
            "id": "milhq_secure_comms_crypto",
            "parent_id": "milhq_command_comms",
            "label": "Secure Communications, Crypto, and Message Handling",
            "category": "safety",
            "description": "Communications and trust services intended to preserve confidentiality, integrity, and authenticity across sensitive workflows.",
        },
        {
            "id": "milhq_network_boundaries",
            "parent_id": None,
            "label": "Networking, Cross-Domain, and External Boundaries",
            "category": "networking",
            "description": "Segmentation, remote sites, coalition links, cross-domain solutions, and boundary protections between enclaves and partners.",
            "telemetry": ["Firewall logs", "Cross-domain approvals", "VPN sessions", "Transfer records"],
        },
        {
            "id": "milhq_enclave_crossdomain",
            "parent_id": "milhq_network_boundaries",
            "label": "Enclaves, Cross-Domain Solutions, and Controlled Transfers",
            "category": "networking",
            "description": "Architectural controls intended to constrain movement between classification levels, mission networks, and partner environments.",
        },
        {
            "id": "milhq_remote_sites_partners",
            "parent_id": "milhq_network_boundaries",
            "label": "Remote Sites, Coalition, and External Interfaces",
            "category": "networking",
            "description": "Operational links between headquarters, remote commands, partners, contractors, and communications providers.",
        },
        {
            "id": "milhq_monitoring_continuity",
            "parent_id": None,
            "label": "Monitoring, OPSEC, and Continuity Process",
            "category": "monitoring",
            "description": "Security operations, OPSEC review, continuity planning, and incident response that shape detection, containment, and mission resilience.",
            "telemetry": ["SIEM alerts", "Audit trails", "Access anomalies", "Continuity exercise records"],
        },
        {
            "id": "milhq_soc_opsec_review",
            "parent_id": "milhq_monitoring_continuity",
            "label": "SOC, Audit, and OPSEC Review",
            "category": "monitoring",
            "description": "Signals and review processes used to detect misuse, unusual access patterns, or anomalous information handling.",
        },
        {
            "id": "milhq_continuity_ir",
            "parent_id": "milhq_monitoring_continuity",
            "label": "Continuity of Operations and Incident Response",
            "category": "process",
            "description": "Fallback and recovery processes determining whether a compromise causes temporary degradation or wider command disruption.",
        },
    ],
}


OIL_REFINERY_CATALOG = {
    "id": "oil_refinery",
    "name": "Oil Refinery",
    "sector": "Oil & Gas / Refining / Process Industry",
    "description": (
        "Reference decomposition of an oil refinery, including process operations, tank farms and loading, DCS and SIS layers, "
        "lab and maintenance systems, vendor access, and turnaround or emergency-response dependencies."
    ),
    "context_presets": ["oil_refinery"],
    "nodes": [
        {
            "id": "refinery_people_roles",
            "parent_id": None,
            "label": "People, Operations, and Trusted Parties",
            "category": "people",
            "description": "Console operators, process engineers, maintenance teams, turnaround contractors, and OEMs shaping access and process trust.",
            "attack_surfaces": ["Permit-to-work", "Turnaround access", "Vendor trust", "Shift handovers"],
        },
        {
            "id": "refinery_ops_engineers",
            "parent_id": "refinery_people_roles",
            "label": "Console Operators, Process Engineers, and Field Operations",
            "category": "people",
            "description": "Operational personnel responsible for unit state, setpoints, alarms, and abnormal-event handling across the refinery.",
        },
        {
            "id": "refinery_turnaround_vendors",
            "parent_id": "refinery_people_roles",
            "label": "Turnaround Contractors, OEMs, and Specialist Vendors",
            "category": "people",
            "description": "Short-term and specialist teams with temporary but high-impact physical or logical access during maintenance windows.",
        },
        {
            "id": "refinery_physical_process",
            "parent_id": None,
            "label": "Process Units, Tank Farm, and Physical Access",
            "category": "physical",
            "description": "Process units, storage tanks, loading racks, substations, field cabinets, and physical access into control or instrument systems.",
            "telemetry": ["Gas detectors", "Perimeter alarms", "Camera feeds", "Work permits"],
        },
        {
            "id": "refinery_process_units",
            "parent_id": "refinery_physical_process",
            "label": "Crude Unit, Conversion Units, and Utility Systems",
            "category": "physical",
            "description": "Core refining processes and supporting utilities whose manipulation can create product loss, unsafe states, or extended outage.",
        },
        {
            "id": "refinery_tankfarm_loading",
            "parent_id": "refinery_physical_process",
            "label": "Tank Farm, Blending, and Loading Operations",
            "category": "service",
            "description": "Storage, transfer, blending, and product-dispatch systems with direct operational and commercial significance.",
        },
        {
            "id": "refinery_ot_control",
            "parent_id": None,
            "label": "DCS, SIS, and Process Control",
            "category": "ot",
            "description": "DCS, PLCs, HMIs, SIS, analyzers, historians, and engineering workstations running refinery process control and safety layers.",
            "attack_surfaces": ["Engineering stations", "Controller downloads", "Safety logic changes", "Analyzer trust"],
        },
        {
            "id": "refinery_dcs_hmi_eng",
            "parent_id": "refinery_ot_control",
            "label": "DCS, HMIs, Historians, and Engineering Workstations",
            "category": "ot",
            "description": "Supervisory and engineering systems used to monitor, tune, and reconfigure refining operations.",
        },
        {
            "id": "refinery_sis_plc_analyzers",
            "parent_id": "refinery_ot_control",
            "label": "SIS, PLCs, Analyzers, and Field Instrumentation",
            "category": "safety",
            "description": "Protective and control layers governing shutdowns, interlocks, and trust in process-state measurements.",
            "common_protocols": ["Modbus", "OPC UA", "PROFINET", "HART/IP"],
        },
        {
            "id": "refinery_it_business",
            "parent_id": None,
            "label": "Plant IT, Maintenance, and Laboratory Systems",
            "category": "it",
            "description": "Identity, maintenance management, laboratory systems, document control, and business-support tooling intersecting with operations.",
            "attack_surfaces": ["Identity workflows", "LIMS access", "Maintenance records", "Patch or file transfer paths"],
        },
        {
            "id": "refinery_identity_maintenance",
            "parent_id": "refinery_it_business",
            "label": "Identity, Maintenance, and Work Management",
            "category": "it",
            "description": "Enterprise and plant services that influence who can access the refinery and when work is expected or approved.",
        },
        {
            "id": "refinery_lims_docs",
            "parent_id": "refinery_it_business",
            "label": "LIMS, Product Quality, and Documentation",
            "category": "service",
            "description": "Laboratory, product-quality, and documentation systems used to assess refinery outputs and preserve operational evidence.",
        },
        {
            "id": "refinery_network_remote",
            "parent_id": None,
            "label": "Networking, Remote Access, and Industrial Communications",
            "category": "networking",
            "description": "Plant DMZs, unit networks, serial gateways, remote support, and communications across process, tank farm, and utility environments.",
            "telemetry": ["Firewall logs", "Remote access events", "Switch changes", "Network monitoring"],
        },
        {
            "id": "refinery_dmz_unit_networks",
            "parent_id": "refinery_network_remote",
            "label": "Plant DMZ, Unit Networks, and Shared Services",
            "category": "networking",
            "description": "Architectural boundaries intended to limit spread between enterprise, maintenance, and refinery process environments.",
        },
        {
            "id": "refinery_vendor_support_paths",
            "parent_id": "refinery_network_remote",
            "label": "Vendor Support, Temporary Access, and Transfer Paths",
            "category": "networking",
            "description": "Trusted support and file-transfer pathways used during maintenance, troubleshooting, and turnaround activity.",
        },
        {
            "id": "refinery_monitoring_recovery",
            "parent_id": None,
            "label": "Monitoring, Safety, and Recovery Process",
            "category": "monitoring",
            "description": "Alarm review, SOE analysis, safety escalation, turnaround management, and incident response shaping detection and restoration.",
            "telemetry": ["Alarm journals", "SOE logs", "Historian trends", "Turnaround records"],
        },
        {
            "id": "refinery_alarm_event_review",
            "parent_id": "refinery_monitoring_recovery",
            "label": "Alarm Management, Event Sequences, and Visibility",
            "category": "monitoring",
            "description": "Operational evidence used to distinguish equipment failure, process upsets, and malicious manipulation across units.",
        },
        {
            "id": "refinery_turnaround_emergency",
            "parent_id": "refinery_monitoring_recovery",
            "label": "Turnaround, Emergency Shutdown, and Incident Response",
            "category": "process",
            "description": "High-risk workflows that can provide cover for malicious change or determine whether the refinery fails safe and recovers cleanly.",
        },
    ],
}


DRILLING_RIG_CATALOG = {
    "id": "drilling_rig",
    "name": "Drilling Rig",
    "sector": "Oil & Gas / Upstream / Drilling",
    "description": (
        "Reference decomposition of a drilling rig environment, including rig crew and contractors, drilling control and well-control systems, "
        "physical rig spaces, communications and remote support, and emergency or safety-critical response dependencies."
    ),
    "context_presets": ["drilling_rig"],
    "nodes": [
        {
            "id": "rig_people_roles",
            "parent_id": None,
            "label": "People, Rig Operations, and Trusted Parties",
            "category": "people",
            "description": "Rig crews, drilling engineers, directional drilling teams, mud logging providers, and OEM vendors influencing well-control trust.",
            "attack_surfaces": ["Shift handovers", "Vendor trust", "Remote support", "Permit-to-work"],
        },
        {
            "id": "rig_drillers_engineers",
            "parent_id": "rig_people_roles",
            "label": "Drillers, Toolpushers, and Wellsite Engineers",
            "category": "people",
            "description": "Operational staff responsible for rig state, drilling parameters, and abnormal-event response during critical well operations.",
        },
        {
            "id": "rig_contractors_service_companies",
            "parent_id": "rig_people_roles",
            "label": "Service Companies, OEMs, and Contractors",
            "category": "people",
            "description": "Third parties maintaining rig controls, BOP systems, MWD or LWD tooling, mud systems, and remote diagnostics.",
            "management_interfaces": ["Vendor laptops", "Support portals", "Field service tools"],
        },
        {
            "id": "rig_physical_access",
            "parent_id": None,
            "label": "Physical Rig, Wellsite, and Equipment Access",
            "category": "physical",
            "description": "Drill floor, doghouse, control cabins, equipment rooms, BOP interfaces, and physical paths into drilling and safety systems.",
            "telemetry": ["Access logs", "CCTV", "Equipment alarms", "Permit records"],
        },
        {
            "id": "rig_drillfloor_control_cabins",
            "parent_id": "rig_physical_access",
            "label": "Drill Floor, Doghouse, and Control Cabins",
            "category": "physical",
            "description": "Operator spaces and local control points where drilling parameters and safety actions can be manipulated directly.",
        },
        {
            "id": "rig_bop_power_utilities",
            "parent_id": "rig_physical_access",
            "label": "BOP Interfaces, Power, and Utility Systems",
            "category": "service",
            "description": "Well-control hardware access points, rig power systems, and supporting utilities needed to sustain safe operations.",
        },
        {
            "id": "rig_ot_control",
            "parent_id": None,
            "label": "Drilling Control, BOP, and Process Systems",
            "category": "ot",
            "description": "Rig control systems, PLCs, HMIs, BOP controls, mud systems, and monitoring platforms governing drilling and well control.",
            "attack_surfaces": ["Engineering access", "Controller downloads", "Operator HMIs", "Sensor trust"],
        },
        {
            "id": "rig_plc_hmi_drilling",
            "parent_id": "rig_ot_control",
            "label": "PLCs, HMIs, and Drilling Automation",
            "category": "ot",
            "description": "Supervisory and local control systems used to monitor and adjust drilling, circulation, hoisting, and related rig functions.",
            "common_protocols": ["Modbus", "OPC UA", "PROFINET", "EtherNet/IP"],
        },
        {
            "id": "rig_bop_safety_sensors",
            "parent_id": "rig_ot_control",
            "label": "BOP Control, Well-Control Safety, and Sensors",
            "category": "safety",
            "description": "Safety-critical systems and instrumentation intended to prevent loss of well control, blowout, or uncontrolled release.",
        },
        {
            "id": "rig_it_comms",
            "parent_id": None,
            "label": "Rig IT, Communications, and Remote Support",
            "category": "networking",
            "description": "Rig networking, satcom or microwave backhaul, remote operations support, and file-transfer paths to shore or field offices.",
            "telemetry": ["VPN logs", "Satcom alarms", "Firewall events", "Remote sessions"],
        },
        {
            "id": "rig_satcom_remote_ops",
            "parent_id": "rig_it_comms",
            "label": "Satellite Links, Remote Ops, and Shore Connectivity",
            "category": "networking",
            "description": "Operational links between the rig, remote drilling centers, vendors, and enterprise support environments.",
        },
        {
            "id": "rig_it_support_records",
            "parent_id": "rig_it_comms",
            "label": "IT Support, Records, and Reporting Systems",
            "category": "it",
            "description": "Identity, maintenance, reporting, and engineering record systems adjacent to rig operations and trusted workflows.",
        },
        {
            "id": "rig_monitoring_response",
            "parent_id": None,
            "label": "Monitoring, Safety, and Emergency Response",
            "category": "monitoring",
            "description": "Alarm review, kick detection, emergency drills, and well-control response processes that shape detection and consequence management.",
            "telemetry": ["Alarm journals", "Well-control trends", "Event logs", "Drill records"],
        },
        {
            "id": "rig_kick_detection_visibility",
            "parent_id": "rig_monitoring_response",
            "label": "Kick Detection, Alarm Visibility, and Event Review",
            "category": "monitoring",
            "description": "Operational evidence used to separate sensor faults, drilling anomalies, and deliberate manipulation of well-control inputs.",
        },
        {
            "id": "rig_emergency_shutdown_response",
            "parent_id": "rig_monitoring_response",
            "label": "Emergency Shutdown, Well-Control, and Incident Response",
            "category": "process",
            "description": "Critical procedures determining whether the rig fails safe during loss-of-control events or broader operational compromise.",
        },
    ],
}


DEFENCE_MANUFACTURING_PLANT_CATALOG = {
    "id": "defence_manufacturing_plant",
    "name": "Defence Manufacturing Plant",
    "sector": "Defence Industry / Secure Manufacturing / Industrial OT",
    "description": (
        "Reference decomposition of a defence manufacturing plant, including secure production operations, industrial control and test systems, "
        "quality and traceability workflows, protected documentation, and supplier or program-security boundaries."
    ),
    "context_presets": ["defence_manufacturing_plant"],
    "nodes": [
        {
            "id": "defmfg_people_roles",
            "parent_id": None,
            "label": "People, Secure Operations, and Trusted Parties",
            "category": "people",
            "description": "Production leaders, cleared engineers, quality teams, security staff, integrators, and specialist contractors influencing trust and access.",
            "attack_surfaces": ["Cleared access", "Program exceptions", "Contractor trust", "Temporary maintenance access"],
        },
        {
            "id": "defmfg_ops_quality_security",
            "parent_id": "defmfg_people_roles",
            "label": "Production, Quality, and Security Personnel",
            "category": "people",
            "description": "Staff responsible for secure production, quality sign-off, inspection, and handling of sensitive equipment or data.",
        },
        {
            "id": "defmfg_vendors_integrators",
            "parent_id": "defmfg_people_roles",
            "label": "Vendors, Integrators, and Specialist Contractors",
            "category": "people",
            "description": "Trusted external parties maintaining industrial equipment, test rigs, secure tooling, and manufacturing support systems.",
        },
        {
            "id": "defmfg_physical_secure",
            "parent_id": None,
            "label": "Physical Security, Production Areas, and Storage",
            "category": "physical",
            "description": "Controlled production halls, secure stores, test areas, loading bays, and physical paths into industrial and support systems.",
            "telemetry": ["Badge logs", "CCTV", "Visitor records", "Asset movement logs"],
        },
        {
            "id": "defmfg_secure_lines_test_cells",
            "parent_id": "defmfg_physical_secure",
            "label": "Secure Production Lines, Test Cells, and Labs",
            "category": "physical",
            "description": "Manufacturing and test areas where sabotage, tampering, or quality masking can affect sensitive defence outputs.",
        },
        {
            "id": "defmfg_storage_shipping",
            "parent_id": "defmfg_physical_secure",
            "label": "Storage, Serialized Components, and Shipping",
            "category": "service",
            "description": "Secure inventory, serialized components, spares, and dispatch workflows affecting traceability and chain of custody.",
        },
        {
            "id": "defmfg_ot_control",
            "parent_id": None,
            "label": "Industrial Control, Robotics, and Test Systems",
            "category": "ot",
            "description": "PLCs, robot cells, test benches, engineering workstations, and machine control systems operating secure production processes.",
            "attack_surfaces": ["Engineering stations", "Robot or test-cell programming", "PLC downloads", "Instrument trust"],
        },
        {
            "id": "defmfg_plc_robotics_test",
            "parent_id": "defmfg_ot_control",
            "label": "PLCs, Robotics, and Automated Test Rigs",
            "category": "ot",
            "description": "Industrial automation and test systems controlling fabrication, integration, acceptance testing, and operational validation.",
            "common_protocols": ["PROFINET", "EtherNet/IP", "OPC UA", "Modbus TCP"],
        },
        {
            "id": "defmfg_safety_quality_sensors",
            "parent_id": "defmfg_ot_control",
            "label": "Safety Systems, Inspection, and Instrumentation",
            "category": "safety",
            "description": "Protective and quality-assurance instrumentation used to detect unsafe conditions, manufacturing drift, or out-of-spec components.",
        },
        {
            "id": "defmfg_it_program_data",
            "parent_id": None,
            "label": "Program IT, Documentation, and Traceability Systems",
            "category": "it",
            "description": "Program networks, quality records, PLM, secure documentation, and controlled data repositories that shape production trust.",
            "attack_surfaces": ["PLM access", "Traceability records", "Program documents", "Identity admin"],
        },
        {
            "id": "defmfg_plm_records",
            "parent_id": "defmfg_it_program_data",
            "label": "PLM, Quality Records, and Engineering Documentation",
            "category": "it",
            "description": "Systems holding design data, production records, waivers, and traceability information with both operational and intelligence value.",
        },
        {
            "id": "defmfg_identity_program_workflows",
            "parent_id": "defmfg_it_program_data",
            "label": "Identity, Program Workflow, and Access Administration",
            "category": "service",
            "description": "Administrative systems governing who can access restricted programs, tooling, and production environments.",
        },
        {
            "id": "defmfg_network_supplier",
            "parent_id": None,
            "label": "Networking, Supplier Interfaces, and Secure Boundaries",
            "category": "networking",
            "description": "Segmentation, remote vendor access, supplier data exchange, and protected program boundaries between enterprise and production systems.",
            "telemetry": ["Firewall logs", "Transfer approvals", "Remote sessions", "Network monitoring"],
        },
        {
            "id": "defmfg_segments_supplier_links",
            "parent_id": "defmfg_network_supplier",
            "label": "Secure Segments, Supplier Links, and Controlled Transfers",
            "category": "networking",
            "description": "Architectural controls intended to constrain movement between secure manufacturing, enterprise services, and suppliers.",
        },
        {
            "id": "defmfg_vendor_remote_paths",
            "parent_id": "defmfg_network_supplier",
            "label": "Vendor Support, Temporary Access, and Service Tooling",
            "category": "networking",
            "description": "Trusted remote and temporary support pathways used for diagnostics, maintenance, and acceptance testing.",
        },
        {
            "id": "defmfg_monitoring_compliance",
            "parent_id": None,
            "label": "Monitoring, Security, and Program Recovery Process",
            "category": "monitoring",
            "description": "Security monitoring, quality investigations, asset-accountability workflows, and incident response shaping containment and confidence.",
            "telemetry": ["Audit trails", "Quality deviations", "Security alerts", "Asset accountability records"],
        },
        {
            "id": "defmfg_audit_quality_visibility",
            "parent_id": "defmfg_monitoring_compliance",
            "label": "Audit Trails, Quality Visibility, and Security Review",
            "category": "monitoring",
            "description": "Evidence used to detect unauthorised changes, tampering, or attempts to hide compromised outputs within accepted workflows.",
        },
        {
            "id": "defmfg_incident_recovery",
            "parent_id": "defmfg_monitoring_compliance",
            "label": "Incident Response, Containment, and Program Recovery",
            "category": "process",
            "description": "Response and continuity procedures determining whether compromise is isolated quickly or cascades into broader production and program impact.",
        },
    ],
}


SHIPYARD_NAVAL_BASE_CATALOG = {
    "id": "shipyard_naval_base",
    "name": "Shipyard / Naval Base",
    "sector": "Maritime / Naval / Industrial and Base Operations",
    "description": (
        "Reference decomposition of a shipyard or naval base, including dockyard operations, vessel and maintenance infrastructure, "
        "base support systems, industrial control environments, logistics and partner interfaces, and emergency or continuity processes."
    ),
    "context_presets": ["shipyard_naval_base"],
    "nodes": [
        {
            "id": "shipyard_people_roles",
            "parent_id": None,
            "label": "People, Base Operations, and Trusted Parties",
            "category": "people",
            "description": "Dockyard staff, base operations teams, naval support personnel, contractors, and shipbuilders influencing trust and restoration.",
            "attack_surfaces": ["Badge approvals", "Contractor trust", "Maintenance windows", "Operational exceptions"],
        },
        {
            "id": "shipyard_ops_maintenance_staff",
            "parent_id": "shipyard_people_roles",
            "label": "Dockyard Operations, Maintenance, and Vessel Support",
            "category": "people",
            "description": "Teams coordinating dry dock operations, maintenance planning, vessel support, and abnormal-event response.",
        },
        {
            "id": "shipyard_vendors_tenants",
            "parent_id": "shipyard_people_roles",
            "label": "Vendors, Tenants, and Specialist Contractors",
            "category": "people",
            "description": "Trusted external parties maintaining cranes, shore power, communications, logistics systems, and industrial equipment.",
        },
        {
            "id": "shipyard_physical_base",
            "parent_id": None,
            "label": "Physical Base, Docks, and Restricted Areas",
            "category": "physical",
            "description": "Perimeter controls, piers, dry docks, warehouses, workshops, and restricted or waterside access paths into critical systems.",
            "telemetry": ["Gate logs", "CCTV", "Waterside alarms", "Visitor or escort records"],
        },
        {
            "id": "shipyard_docks_workshops",
            "parent_id": "shipyard_physical_base",
            "label": "Docks, Dry Docks, Workshops, and Maintenance Spaces",
            "category": "physical",
            "description": "Operational zones where ships, industrial machinery, and maintenance workflows converge with direct consequence potential.",
        },
        {
            "id": "shipyard_storage_utilities",
            "parent_id": "shipyard_physical_base",
            "label": "Storage, Shore Power, Fuel, and Utility Support",
            "category": "service",
            "description": "Warehousing, shore services, utility systems, and fueling or support infrastructure required to sustain base operations.",
        },
        {
            "id": "shipyard_ot_industrial",
            "parent_id": None,
            "label": "Industrial Control, Cranes, and Dock Systems",
            "category": "ot",
            "description": "PLCs, crane controls, dry-dock systems, power-management, and industrial automation supporting repair and vessel movement.",
            "attack_surfaces": ["Engineering access", "PLC programming", "Crane safety systems", "Industrial HMIs"],
        },
        {
            "id": "shipyard_cranes_drydock_plc",
            "parent_id": "shipyard_ot_industrial",
            "label": "Cranes, Dry-Dock Controls, and Industrial PLCs",
            "category": "ot",
            "description": "Industrial systems controlling lifts, dock services, pumps, gates, and heavy equipment used around ships and base facilities.",
            "common_protocols": ["PROFINET", "Modbus", "OPC UA", "EtherNet/IP"],
        },
        {
            "id": "shipyard_safety_environmental",
            "parent_id": "shipyard_ot_industrial",
            "label": "Safety, Environmental, and Utility Monitoring",
            "category": "safety",
            "description": "Protective systems and instrumentation used to detect hazardous conditions, flooding, power faults, or unsafe dockyard states.",
        },
        {
            "id": "shipyard_it_logistics",
            "parent_id": None,
            "label": "Base IT, Logistics, and Work Management Systems",
            "category": "it",
            "description": "Maintenance planning, logistics, identity, tenant coordination, and documentation systems that shape expected operations.",
            "attack_surfaces": ["Identity admin", "Work orders", "Logistics systems", "Document access"],
        },
        {
            "id": "shipyard_workorders_logistics",
            "parent_id": "shipyard_it_logistics",
            "label": "Work Orders, Logistics, and Asset Tracking",
            "category": "it",
            "description": "Systems coordinating maintenance, spares, movement, and asset state across ships, facilities, and contractors.",
        },
        {
            "id": "shipyard_identity_docs",
            "parent_id": "shipyard_it_logistics",
            "label": "Identity, Documentation, and Access Administration",
            "category": "service",
            "description": "Administrative services governing who can access shipyard facilities, tenant systems, and maintenance records.",
        },
        {
            "id": "shipyard_network_partner",
            "parent_id": None,
            "label": "Networking, Waterside Communications, and Partner Interfaces",
            "category": "networking",
            "description": "Base LANs, partner links, wireless, remote support, and communications paths across dockside, industrial, and enterprise systems.",
            "telemetry": ["Firewall logs", "Wireless alerts", "Partner sessions", "Comms monitoring"],
        },
        {
            "id": "shipyard_partner_remote_links",
            "parent_id": "shipyard_network_partner",
            "label": "Partner, Tenant, and Remote Support Links",
            "category": "networking",
            "description": "Data and trust paths between the base, shipbuilders, tenants, vendors, and remote maintenance or logistics providers.",
        },
        {
            "id": "shipyard_waterside_mobile_comms",
            "parent_id": "shipyard_network_partner",
            "label": "Waterside, Wireless, and Operational Communications",
            "category": "networking",
            "description": "Mobile and waterside communications used by base operations, maintenance teams, cranes, and support units.",
        },
        {
            "id": "shipyard_monitoring_recovery",
            "parent_id": None,
            "label": "Monitoring, Security, and Continuity Process",
            "category": "monitoring",
            "description": "Security operations, dockyard monitoring, safety response, and continuity workflows affecting detection and mission or industrial resilience.",
            "telemetry": ["SOC alerts", "Industrial alarms", "Incident logs", "Continuity exercise records"],
        },
        {
            "id": "shipyard_security_operational_visibility",
            "parent_id": "shipyard_monitoring_recovery",
            "label": "Security Monitoring, Alarms, and Operational Visibility",
            "category": "monitoring",
            "description": "Signals used to detect suspicious movement, industrial anomalies, partner misuse, or attempts to disrupt maintenance and ship support.",
        },
        {
            "id": "shipyard_incident_continuity",
            "parent_id": "shipyard_monitoring_recovery",
            "label": "Incident Response, Base Continuity, and Recovery",
            "category": "process",
            "description": "Response and fallback processes determining whether a compromise becomes a contained maintenance issue or a wider base disruption.",
        },
    ],
}
