"""
Export service: JSON, CSV, Markdown, PDF generation.
All export is local — no cloud dependencies.
"""
import csv
import io
import json
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak


def export_json(project: dict, nodes: list[dict]) -> str:
    """Export full project as JSON."""
    data = {
        "export_version": "1.0",
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "project": project,
        "nodes": nodes,
    }
    return json.dumps(data, indent=2, default=str)


def export_csv(nodes: list[dict]) -> str:
    """Export nodes as CSV."""
    output = io.StringIO()
    if not nodes:
        return ""

    fields = [
        "id", "parent_id", "node_type", "title", "description", "logic_type",
        "status", "likelihood", "impact", "effort", "exploitability",
        "detectability", "confidence", "inherent_risk", "residual_risk",
        "threat_category", "attack_surface", "platform", "required_access",
        "required_privileges", "required_skill",
    ]
    writer = csv.DictWriter(output, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    for node in nodes:
        writer.writerow({k: node.get(k, "") for k in fields})

    return output.getvalue()


def export_markdown(project: dict, nodes: list[dict], report_type: str = "technical") -> str:
    """Generate a Markdown report."""
    lines = []
    name = project.get("name", "Untitled")
    objective = project.get("root_objective", "Not specified")
    context = project.get("context_preset", "general")

    lines.append(f"# Attack Tree Report: {name}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Context:** {context}")
    lines.append(f"**Root Objective:** {objective}")
    lines.append("")

    # Build tree hierarchy
    root_nodes = [n for n in nodes if not n.get("parent_id")]
    if not root_nodes and nodes:
        root_nodes = [nodes[0]]

    def _render_node(node: dict, depth: int = 0):
        indent = "  " * depth
        risk = node.get("inherent_risk") or node.get("rolled_up_risk") or "—"
        status = node.get("status", "draft")
        ntype = node.get("node_type", "")
        logic = node.get("logic_type", "OR")

        lines.append(f"{indent}- **[{ntype}]** {node.get('title', 'Untitled')} "
                     f"({logic}) — Risk: {risk} | Status: {status}")

        if node.get("description"):
            lines.append(f"{indent}  > {node['description']}")

        # Mitigations
        for m in node.get("mitigations", []):
            lines.append(f"{indent}  - Mitigation: {m.get('title', '')} "
                         f"(effectiveness: {m.get('effectiveness', 0):.0%})")

        # Reference mappings
        for r in node.get("reference_mappings", []):
            lines.append(f"{indent}  - {r.get('framework', '').upper()}: "
                         f"{r.get('ref_id', '')} — {r.get('ref_name', '')}")

        # Render children
        children = [n for n in nodes if n.get("parent_id") == node.get("id")]
        children.sort(key=lambda x: x.get("sort_order", 0))
        for child in children:
            _render_node(child, depth + 1)

    lines.append("## Attack Tree Structure")
    lines.append("")
    for root in root_nodes:
        _render_node(root)
    lines.append("")

    # Risk summary
    scored_nodes = [n for n in nodes if n.get("inherent_risk") is not None]
    if scored_nodes:
        scored_nodes.sort(key=lambda x: x.get("inherent_risk", 0), reverse=True)
        lines.append("## Top Risks")
        lines.append("")
        lines.append("| Node | Type | Risk | Status |")
        lines.append("|------|------|------|--------|")
        for n in scored_nodes[:10]:
            lines.append(f"| {n.get('title', '')} | {n.get('node_type', '')} | "
                         f"{n.get('inherent_risk', '—')} | {n.get('status', '')} |")
        lines.append("")

    # Unmitigated nodes
    unmitigated = [n for n in nodes
                   if n.get("inherent_risk") is not None
                   and not n.get("mitigations")]
    if unmitigated:
        lines.append("## Unmitigated Attack Steps")
        lines.append("")
        for n in unmitigated[:10]:
            lines.append(f"- **{n.get('title', '')}** — Risk: {n.get('inherent_risk', '—')}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by AttackTree Builder*")
    return "\n".join(lines)


def export_pdf(project: dict, nodes: list[dict], report_type: str = "technical") -> bytes:
    """Generate a PDF report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           topMargin=20*mm, bottomMargin=20*mm,
                           leftMargin=15*mm, rightMargin=15*mm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=10)
    heading_style = ParagraphStyle("CustomH2", parent=styles["Heading2"], fontSize=14, spaceAfter=8)
    body_style = styles["BodyText"]
    small_style = ParagraphStyle("Small", parent=body_style, fontSize=8, textColor=colors.grey)

    story = []

    # Title page
    name = project.get("name", "Untitled")
    story.append(Paragraph(f"Attack Tree Report", title_style))
    story.append(Paragraph(f"<b>{name}</b>", styles["Heading1"]))
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"<b>Root Objective:</b> {project.get('root_objective', 'Not specified')}", body_style))
    story.append(Paragraph(f"<b>Context:</b> {project.get('context_preset', 'general')}", body_style))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(Spacer(1, 20))

    # Risk Summary Table
    scored = [n for n in nodes if n.get("inherent_risk") is not None]
    if scored:
        scored.sort(key=lambda x: x.get("inherent_risk", 0), reverse=True)
        story.append(Paragraph("Top Risks", heading_style))

        table_data = [["Node", "Type", "Risk", "Status"]]
        for n in scored[:15]:
            table_data.append([
                n.get("title", "")[:50],
                n.get("node_type", ""),
                str(n.get("inherent_risk", "—")),
                n.get("status", ""),
            ])

        t = Table(table_data, colWidths=[200, 80, 50, 70])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ]))
        story.append(t)
        story.append(Spacer(1, 15))

    # Node listing
    story.append(Paragraph("Attack Tree Nodes", heading_style))
    root_nodes = [n for n in nodes if not n.get("parent_id")]

    def _add_node_to_story(node: dict, depth: int = 0):
        prefix = "→ " * depth
        risk_str = str(node.get("inherent_risk") or node.get("rolled_up_risk") or "—")
        text = (f"{prefix}<b>[{node.get('node_type', '')}]</b> {node.get('title', '')} "
                f"({node.get('logic_type', 'OR')}) — Risk: {risk_str}")
        story.append(Paragraph(text, body_style))

        if node.get("description"):
            story.append(Paragraph(f"{prefix}  {node['description'][:200]}", small_style))

        children = [n for n in nodes if n.get("parent_id") == node.get("id")]
        children.sort(key=lambda x: x.get("sort_order", 0))
        for child in children:
            _add_node_to_story(child, depth + 1)

    for root in root_nodes:
        _add_node_to_story(root)

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by AttackTree Builder", small_style))

    doc.build(story)
    return buffer.getvalue()
